### ISSUE TITLE
editor: temporary files are not deleted

### ISSUE THREAD

**Issue by fd0** [tridactyl/tridactyl#1005]
*   Brief description of the problem: Using an external editor like `gvim` for editing textarea fields leaves temporary files behind.

*   Steps to reproduce:
 1. Install native extensions
 2. Edit a textarea with `:editor`, save, quit the editor
 3. Observe the temporary file in `/tmp`: `ls -al /tmp/tmp_*`

*   Tridactyl version (`:version`): `1.14.0-1.14.0`

*   Firefox version (Top right menu > Help > About Firefox): `60.2.0esr (64-bit)`

*   URL of the website the bug happens on: internal, cannot disclose

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/fd0/5479848337411aa4fdd39ea04990c29d

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
bind K tabnext
bind J tabprev

" Sane hinting mode
set hintfiltermode vimperator-reflow
set hintchars 4327895610

set editorcmd gvim -c "set tw=76"
```

**Comment by bovine3dom** [comment]
This is on purpose - the idea is that if something goes wrong in the transfer of the text back to the browser, you can still open the file.

Deletion of the temporary files is left as an exercise for your operating system.

**Comment by glacambre** [comment]
We could have [editor()](https://github.com/tridactyl/tridactyl/blob/a0ac1a2878c71627ddd44bd5d6aab950241912ab/src/excmds.ts#L198) return a `[filepath, content]` tuple since it doesn't return anything useful for now. Then users could do something like
```
alias editor_rm composite editor | jsb -p tri.native.run(`rm -f  ${JS_ARG[0]}`)
```

**Comment by glacambre** [comment]
The suggestion I gave has been implemented, this means that you can now use
```
 alias editor_rm composite editor | jsb -p tri.native.run(`rm -f '${JS_ARG[0]}'`)
 bind --mode=insert <C-i> editor_rm
 bind --mode=input <C-i> editor_rm
```
In order to implement the behavior you want. Please let us know if this is not enough.

**Comment by fd0** [comment]
Cool, thanks!

**Comment by madduck** [comment]
I definitely agree that there is utility in keeping a backup of the file in case something goes wrong. In fact, I've had the following `editorcmd` from back in the Vimperator days do the same for me:

```
set editorcmd x-terminal-emulator -name tridactyl-edit -e vim -c "autocmd BufWritePost <buffer> exe 'write ' . expand('$TMPDIR') . '/tridactyl-backups/' . strftime('%Y-%m-%d-%H%M%S') . '.txt'" '+set wrap linebreak textwidth=0' '+normal!%lGzv%c|la' %f +start
```

The proposed solution is a hack. I personally think it's the job of the editor to keep a backup, not that of Tridactyl. And I also don't think it's fair to say that someone else has to clean up. Just my 2¢ to this closed issue.

**Comment by bovine3dom** [comment]
They're not backups, they're temporary files. We make them with `mkstmp` so the OS is promising us that it will tidy them up soon after they aren't in use.

The only distribution I know of that doesn't tidy up tmp is Arch, because you're expected to set it up yourself. What OS are you on?

**Comment by madduck** [comment]
I am not aware of any OS "promising" cleaning up files. It is true that most are set up to auto-clean `/tmp` on boot, but that is not enough if

1. the machine is hardly ever booted;
2. or the user chooses to set `TMPDIR` to something else, maybe because they don't want to leak information even about which temporary files are being created when to other users.

I am on Debian, and both these two points apply. I do have my `TMPDIR` auto-cleaned of files older than 3 days. It still means that I get *a lot* of files in there, and I actually often use `TMPDIR` for all kinds of things. Hence my desire to be able to specify a separate directory for backups.

**Comment by bovine3dom** [comment]
I was using promise in a very lazy sense. It's more like it's not the program that calls `mktemp` that is responsible for tidying up, in my humble opinion.

> Hence my desire to be able to specify a separate directory for backups

`mkstemp` should already support `$TMPDIR`. If you start Firefox with it set we should respect it.

I think I just fundamentally disagree about whose responsibility it is to tidy up temporary files. If someone's system is set up to tidy up temporary files on reboot but they never reboot, their system is misconfigured, right?

**Comment by glacambre** [comment]
>I think I just fundamentally disagree about whose responsibility it is to tidy up temporary files.

The documentation of the python function being used clearly states that it is the program's responsibility to clean up temporary files though.

Old messenger:

https://github.com/tridactyl/tridactyl/blob/e84df4f527ce53b736bc7a5ab76eb78d978e69eb/native/native_main.py#L492-L495

[mkstemp](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp):
>Unlike TemporaryFile(), the user of mkstemp() is responsible for deleting the temporary file when done with it.

New messenger:

https://github.com/tridactyl/native_messenger/blob/dcd433ffa31fe85a4a49d9dce788611dd6c8a862/src/native_main.nim#L257-L262

mkstemp is [just a binding to the OS' mkstemp](https://github.com/nim-lang/Nim/blob/version-1-4/lib/posix/posix.nim#L1042-L1047), which [doesn't claim to remove files](https://man7.org/linux/man-pages/man3/mkstemp.3.html).

> If someone's system is set up to tidy up temporary files on reboot but they never reboot, their system is misconfigured, right?

Nope :). The problem is that Tridactyl's definition of "temporary" does not match the OS's definition of "temporary" for temporary files. There is no way for the OS to guess what "temporary" means as different applications will have different definitions. So IMO it really is the application's job to delete files (as it's the only one knowing what "temporary" means).

**Comment by bovine3dom** [comment]
Yeah, looks like I was just wrong about temporary files. Thanks for the correction : )

I'm not sure what we should do instead. Immediate deletion would have lost me hours of work on a few occasions.

**Comment by glacambre** [comment]
>I'm not sure what we should do instead. Immediate deletion would have lost me hours of work on a few occasions.

What are these cases? Could vim's backup and swap files have helped?

**Comment by bovine3dom** [comment]
1. A couple of times, I've been writing a long email through :editor on Zoho Mail and after :wq the Tridactyl logo disappears and nothing happens
2. I'm pretty sure I've lost stuff on GitHub in the same way

(Both before we switched to firenvim's library, but I haven't written much since.)

I think vim's backup only makes a backup of the original file before you edit it, so it wouldn't be useful here. Swap files are deleted on vim exit so no good either.

**Comment by madduck** [comment]
You'd need a write hook, such as [the one I provided above](https://github.com/tridactyl/tridactyl/issues/1005#issuecomment-921451064) to save a backup, or maybe an even better approach would be to write a script that fires off the editor and copies the file to a save location before handing the data back to Tridactyl. The benefit of this would be that it becomes "by design", rather than a behaviour implicit in Tridactyl simply not removing temporary files.

Of course, we could also just rename the files and call them backups from now on, rather than temporary files, and the problem would also be solved. See #3910.

In any case, this certainly does not warrant much of your precious time wasted on philosophical discussions.

**Comment by madduck** [comment]
I had a moment and wrote a little script that can be used as wrapper to save backups. It's attached*, and to be used like this:

```
set editorcmd x-terminal-emulator -name tridactyl-edit -e ~/.config/tridactyl/edit-and-backup %f "vim '+set wrap linebreak textwidth=0' '+normal!%lGzv%c|la' +start"
```

If you don't specify the editor, `editor` is used.

* actually, it's not attached, because Github only lets me attach certain *file types* determined by the file name extension.

```
#!/bin/sh
#
# edit-and-backup
#
# Wrapper for Tridactyl's $editorcmd, which saves a backup before returning
# to Tridactyl.
#
# © 2021 martin f. krafft <madduck@madduck.net>
# Released under the Apache Licence 2.0.
#
set -eu

BACKUPDIR=${TMPDIR:-/tmp}/tridactyl-backups
mkdir --parent $BACKUPDIR

FILENAME="$1"
EDITOR="${2:-editor}"

eval "$EDITOR" "$FILENAME"

notify() {
  local summary
  summary="$1"; shift
  if command -v notify-send >/dev/null; then
    notify-send "$summary" "$@"
  else
    echo >&2 "$@"
  fi
}

if [ -s "$FILENAME" ]; then

  URL="${FILENAME#*_}"; URL="${URL%%_*}"
  BACKUPFILE="$(mktemp --tmpdir="$BACKUPDIR" $(date +%F-%H%M.%N)-$URL-XXXXXXXX.txt)"
  cat "$FILENAME" > "$BACKUPFILE"

  notify "Tridactyl backup saved" "Saved a backup of your edits to $BACKUPFILE"

else

  notify "Nothing to be saved"

fi

exit 0
```

**Comment by bovine3dom** [comment]
Sorry - I thought I had replied to this.

Thanks for writing that script, it looks good. One thing I'm a bit concerned about is that it won't protect people from editors that exit early - it's very easy to make an editor command that forks itself and then has the original command exit. That means that `:editor` looks like it will work but as soon as you quit everything will be lost.

I think the easiest thing to do is this:

1. Document that the temporary files are retained so people can find them
2. Warn people that they're not deleted by Tridactyl
3. Allow people to specify their own temporary directory
4. Add a command in Tridactyl for deleting all `tmp_.*txt` files in that directory.

`3.` could be somewhat tricky as we'll need to update the native messenger.

**Comment by madduck** [comment]
How does Tridactyl currently protect people from editors that spawn and "exit early"?

> it's very easy to make an editor command that forks itself and then has the original command exit

Indeed. Some programming should be made illegal.

If Tirdactyl currently does not protect against early-exiting editors, then  #3914 would fix this: whenever the file changes, the changes are propagated. Now all we need is a background check so that when the actual editor process quits, we remove the "Tridactyl is editing" stamp, and turn the input read-write.

**Comment by bovine3dom** [comment]
> How does Tridactyl currently protect people from editors that spawn and "exit early"?

The temporary file stays on the file system so you can find it and recover your work.

> Some programming should be made illegal.

I mean easy as in "people do it all the time by accident" :) it's usually as simple as neglecting to give it a flag, e.g. https://github.com/tridactyl/tridactyl/blob/da9bea7edf63dd3ec24bd44c120cb72d6530ee18/src/lib/native.ts#L191

> whenever the file changes, the changes are propagated. Now all we need is a background check so that when the actual editor process quits

I would have implemented so that we stopped listening for changes when the process exited. It seems messy to do anything else - what if they close the editor and then open it again? etc

**Comment by madduck** [comment]
Yes, absolutely… you need to find out when the child process exits. However, I think this should be possible to do by trapping SIGCHLD, no? You're spawning the native messenger, which spawns the editor, which spawns the actual editor… Now if the spawning editor exited, the actual editor would still be in a process group spawned by the native messenger, so the messenger should receive a SIGCHLD when the actual editor quits, no?

**Comment by bovine3dom** [comment]
I honestly don't know. It's plausible but we'd need to make sure it worked across all platforms.

**Comment by glacambre** [comment]
>One thing I'm a bit concerned about is that it won't protect people from editors that exit early - it's very easy to make an editor command that forks itself and then has the original command exit.

If `:editor` returns early, the file is immediately deleted while the actual editor is still open, so when the user `:wq`s, they'll create a new file that will linger around on their drive forever (they might even be warned about the file having been deleted).

**Comment by madduck** [comment]
an editor that returns early is not our problem. there is nothing we can sensibly do to deal with such abhorrent behaviour. the docs should warn about this, and tridactyl might even attempt to catch when the editor exits within a second or two...
