### ISSUE TITLE
Help should explain the meaning of hintfiltermode settings

### ISSUE THREAD

**Issue by jamesblau** [tridactyl/tridactyl#1028]
Pretty much explained in title. Vimperator mode is explained in the readme FAQs and in config.ts, but not in the relevant help section, and -reflow isn't explained anywhere.

**Comment by notJerl** [comment]
Glancing at the code, it appears that `-reflow` is actually currently just an alias of `vimperator`.  Presumably reflow mode isn't finished, so they just made the code that checks which mode is selected return the same as it would for regular `vimperator`.

Relevant code:

    function defaultHintBuilder() {
        switch (config.get("hintfiltermode")) {
            case "simple":
                return buildHintsSimple
            case "vimperator":
                return buildHintsVimperator
            case "vimperator-reflow":
                return buildHintsVimperator
        }
    }

**Comment by jamesblau** [comment]
I was about to edit this to mention that "relatedopenpos" is not explained, either, although this can be guessed from "tabopenpos".

Also: it might be good to mention in the help document that config.ts contains a lot of information that hasn't made it into :help yet.

**Comment by notJerl** [comment]
`vimperator-reflow` is essentially the same as `vimperator`, but when you use link names rather than the numerical hints to select a link, it reflows all the links.  Let's say you've got a bunch of links that are named as A, AB, etc through ZZ.  With `vimperator`, if you press C, it'll simply hide all the hints for links that don't start with the letter C.  With `vimperator-reflow`, if you press C, it'll reflow the hints so that `CA` (or whatever C link is closest to the top of the document) gets reflowed to the hint 1.

**Comment by jamesblau** [comment]
Thanks!

**Comment by glacambre** [comment]
>it might be good to mention in the help document that config.ts contains a lot of information that hasn't made it into :help yet.

I think this is because the build bot is using outdated documentation. Our source files have a link to `/static/docs/classes/_src_config_.default_config.html` but the help pages do not. @bovine3dom this is proably related to the 'delete the build dir' thing we talked about a month ago.

**Comment by bovine3dom** [comment]
Huh. I'll look into it.
