### ISSUE TITLE
RFC: setters for config options

### ISSUE THREAD

**Issue by saulrh** [tridactyl/tridactyl#1043]
Some of our more complex settings have to be interacted with using excmds so that complex checks can be done or other data updated in sync with the config setting. Examples: `:command` needs to check for loops and automatically resolve the argument, `:setsearchkeyword` mangles one of the arguments a bit, `:seturl` does some extra validation. This came up because the perf counter system might need a `:perfcounters activate | deactivate` excmd to interact with some caching logic.

Does it look like there'd be a reasonable way for config options to be given setters, so that this logic can be run as a callback when `:set` is used to update that option? Is that something we'd even want? Vim seems to use the excmds-as-setters pattern pretty often, but I've never really liked it.

**Comment by glacambre** [comment]
>Does it look like there'd be a reasonable way for config options to be given setters, so that this logic can be run as a callback when :set is used to update that option?

I'm not sure how this could be implemented but what we currently do is use `browser.storage.onChanged.addListener` in order to listen for changes to the config and change what needs to be changed.

You could also try to enforce using your `perfcounters` excmd by making writing to the setting impossible with `set`. Not sure how declaring the setting with `setting: never = ("value" as never)` would work once https://github.com/tridactyl/tridactyl/pull/1026 is merged.

**Comment by saulrh** [comment]
> I'm not sure how this could be implemented but what we currently do is use browser.storage.onChanged.addListener in order to listen for changes to the config and change what needs to be changed.

...Oh, that's probably a better way to do it, lol. Closing as "I have a way to do this that actually makes sense inside idiomatic js".
