### ISSUE TITLE
Being too fast in the commandline is punished by completions

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1208]
Steps to reproduce:

Quickly type `o[fragment of site you access often]<Tab><Enter>` -> Tab selects a completion that hasn't been updated, it gets updated and therefore deselected, and then Enter fails the URL check and searches for your fragment on your favourite search engine instead.

Potential solution: <Tab> and <Enter> should be queued up until the keys typed before them have been processed.

I've been catching this quite a bit in the wild.

**Comment by JDGBOLT** [comment]
Yeah, I've encountered this a lot, which has been quite annoying. It especially is apparent when the system is otherwise loaded, so that happens constantly. Another issue I have experienced as of late has been sometimes pressing space isn't registered until later, which causes spaces to get inserted into the wrong locations, so rather than way "white cat" what comes out is "whitec at" or whatever, which is quite an annoyance.

**Comment by glacambre** [comment]
The space problem has been introduced in https://github.com/tridactyl/tridactyl/pull/1123 . It is caused by the excmd dispatching code being too slow. I attempted a crude fix (basically awaiting the end of the previous excmd dispatch before doing anything) and it was incredibly wasteful cpu-wise so I didn't bother submitting a PR for that. I think https://github.com/tridactyl/tridactyl/pull/995 might be able to help with this problem since excmd dispatch won't require going to the background anymore, but the only way to make it completely disappear will be to have a controller directly in the command line.

**Comment by bovine3dom** [comment]
Has improved this #1655 markedly. `o[fragment of site you access often]<Tab><Enter>` can still open a search if you're typing at extreme speeds, but I haven't personally encountered this in the wild. I can't reproduce `<Space>` appearing in the wrong order no matter how hard I try.

I've therefore reduced the priority of this issue. I'll leave it open until we fix it totally.

**Comment by bovine3dom** [comment]
As far as I can tell, this has been fixed in #3196.

Finally, muscle memory is useful again...
