### ISSUE TITLE
hinting is crazy and not working

### ISSUE THREAD

**Issue by ngortheone** [tridactyl/tridactyl#1215]
On some pages, for example on google when I use hinting letters overlap each other. And the letter that is on top is not doing anything.

See example picture: Google home has "B" letter on top, but when I press it nothing happens. "W" also does not do anything. By guessing I can see that "Q" is hidden behind "B", and it does what I want.

This is really convoluted. Is there a way to change this behavior? 

<img width="680" alt="screen shot 2018-12-05 at 11 25 41 pm" src="https://user-images.githubusercontent.com/18271144/49561501-a2f58a00-f8e5-11e8-8765-382a6b1b9677.png">
<!--

**Comment by glacambre** [comment]
This is caused by Tridactyl detecting event handlers on these links and adding hints to trigger them.

As mentioned in https://github.com/tridactyl/tridactyl/issues/1212 you can try changing your hints' style in order to make them slightly smaller, from looking at your screenshot I think it might help a little.

This is a problem we're aware of but there's no real solution to this problem yet. https://github.com/tridactyl/tridactyl/issues/28#issuecomment-346585345 mentions that we plan on adding the ability to switch through hints someday.

**Comment by bovine3dom** [comment]
We should have a setting to use the dumb style of hint without event handlers. That way people could mitigate it on the most annoying sites with `seturl`.
