### ISSUE TITLE
Completion on MacOS broke with 1.14.3. It used to work with 1.14.1. And it still works on Linux.

### ISSUE THREAD

**Issue by MassimoLauria** [tridactyl/tridactyl#1223]
Completion does not work on MacOS  with 1.14.3. It used to work with 1.14.1. And it still works on Linux.

* Steps to reproduce:

Open the browser and type ":ta" and it does not show any command that completes "ta"
The same if I type ":o " or ":tabopen " and it does not show any suggestion for a website  

Tridactyl version (`:version`): 1.14.3-1.14.3
Firefox version: 63.03
URL of the website the bug happens on: it happens on any URL and page

* Result of :viewconfig is here 
https://gist.github.com/MassimoLauria/4dfec7d78070f6f84401c0d9cb634931

Operating system: MacOS
:! echo $PATH in Tridactyl:
/Users/massimo/.pyenv/versions/3.6.5/bin:/usr/local/Cellar/pyenv/1.2.5/libexec:/usr/bin:/bin:/usr/sbin:/sbin

Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

{"cmd": "run", "content": "/Users/massimo/.pyenv/versions/3.6.5/bin:/usr/local/Cellar/pyenv/1.2.5/libexec:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/massimo/.pyenv/shims:/Users/massimo/.pyenv/bin:/Users/massimo/.cabal/bin:/Users/massimo/Library/Haskell/bin:/Users/massimo/.cask/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin\n", "code": 0}

**Comment by MassimoLauria** [comment]
It seems it did fix my issue! What did just happened?

**Comment by bovine3dom** [comment]
@glacambre we should really put in a config updater to clear that setting soon. I think this is the third person we know we broke Tridactyl for.

@MassimoLauria we recently changed the correct internal function to be buffer rather than tab, and left an alias from buffer to tab. You had an alias from tab to buffer, so you had an infinite loop, breaking the completions which expand aliases to find the commands they call and their help.
