### ISSUE TITLE
Minimal userChrome theme now breaks tabbing (CTRL-W, CTRL-TAB, CTRL-T, etc.)

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#1229]
Hi, this is not actually a problem with Tridactyl itself but the [minimal userChrome](https://raw.githubusercontent.com/tridactyl/tridactyl/32a1fd25d4c5a4ef3402bfa460b09ceb91a88345/src/static/css/userChrome-minimal.css) packaged with the repository. I've been using it fine for a couple of months and I love it, but out of nowhere this morning I couldn't use any of the tabbing behavior in Firefox. 

After trying a few things, I narrowed down the problem to this css file, as simply renaming it so it's not active anymore fixes the issue. It appears that CTRL-W, CTRL-(SHIFT)-TAB and CTRL-T (possibly other shortcuts as well) all stop working now when the tab bar is hidden. I am on the beta channel with 65.0b3 but I can confirm the problem is present as well in Nightly as of today.

**Comment by bovine3dom** [comment]
Eugh. Mozilla do promise that they'll break userChrome quite a bit. I hope this is a bug or that there is some easy workaround. You could try asking on https://www.reddit.com/r/FirefoxCSS/ or looking around there.

NB - we probably don't keep that userChrome up-to-date anyway. `guiset` is the recommended way to fiddle with userChrome now.

**Comment by aplaice** [comment]
FWIW it seems that the CSS lines that break Firefox's tab navigation are:

```css
#titlebar {
    display: none !important;
}
```

(For me, they're necessary and sufficient for the breakage to occur.)

Presumably (haven't tested it, as I don't use the native messenger), `guiset titlebar hide` would have the same effect of breaking Firefox's tab navigation, as it uses the same [CSS code](https://github.com/tridactyl/tridactyl/blob/55aadcb/src/lib/css_util.ts#L130).

**Comment by glacambre** [comment]
```css
#titlebar {
    display: none !important;
}
```
Doesn't seem to break anything on my end :/ Are you still experiencing this bug?

**Comment by aplaice** [comment]
The bug is still present with the latest Firefox nightly (`66.0a1 (2019-01-27)`), both on Ubuntu 16.04 and 18.04, with a tiling window manager (XMonad) or with a "normal" DE (XFCE), using the native messenger with `guiset titlebar hide` or setting `userChrome.css` directly, with no other customisation. (I've tested on two separate machines.) Firefox 64, both that from Ubuntu's repos and that installed from Mozilla's website, is unaffected.

FWIW I've never personally used or needed this particular customisation (I had initially commented as I feel responsible for the minimal userChrome as one of the contributors to it), so unless the original reporter is still affected, this might be a "victimless" bug.

**Comment by bovine3dom** [comment]
We should try to make it such that `guiset gui none` fixes a userChrome that has previously been broken by Tridactyl.

When I release 1.4.7, I'll set the minimum version to FF64, which should mean we can stop caring about ESR.

On a personal note, I'll be very sad if we can't fix this. I don't know of any other way of binning window decorations on Windows.

**Comment by bovine3dom** [comment]
FF65 has just been released, so we're probably going to find quite a few people with this issue.

Until we fix it:

- remove any reference to `guiset` from your `tridactylrc` if it exists
- visit about:support
- click "open directory" next to your profile directory
- remove or rename the userChrome.css file in the chrome directory

**Comment by quinoa42** [comment]
Reproduced on Fx65 (actually I run into the same problem when I first tried developer edition one month ago, so I just went back to use Fx64 after that).

**Comment by bovine3dom** [comment]
Closed as we've removed `titlebar` from `guiset`. I didn't trust myself to work out how to remove the rule automatically, so manual intervention is required, as detailed [above](https://github.com/tridactyl/tridactyl/issues/1229#issuecomment-458583919).

If you use `guiset`

**Comment by aplaice** [comment]
I *think* that just switching to using `visibility: collapse` rather than `display: none` fixes the issue of non-functional tab-switching. Based on brief testing on Windows (ugh! :p) it seems to hide the titlebar, as desired. The only mild issue is that with this CSS, using Firefox's "Customise.." to toggle the merging of the Title Bar (the option that's just been added on Linux (`browser.tabs.drawInTitlebar` in `about:config`)) will occasionally, temporarily freeze up the customise interface and part of the UI (but not any webpage content or UI shortcuts). Toggling this option via `about:config` does not cause the freezing up.

```css

:root:not([customizing]) #titlebar {
    visibility: collapse !important;
}
```

(Having `:root:not([customizing])` allows displaying the titlebar when customising, which is sometimes convenient, but doesn't affect the above mentioned bug of customising sometimes freezing up — it occurs both with and without `:root:not([customizing])` present.)

Actually, I'm not sure why `display: none` was used for the titlebar, in the first place, since for everything else we used `visibility: collapse`.

**Comment by thrisp** [comment]
I'm not sure what is going on, but this is still an ongoing issue for me. All tabbing is non functional in a very wacky way.
