### ISSUE TITLE
Can I setting to "Delete to begging of line" with <C-u> in text field?

### ISSUE THREAD

**Issue by nullplus** [tridactyl/tridactyl#1238]
I won't setting to "deleteToBegging" by "bind" command.
What should I do?

## in macOS
macOS have emacs keybindng in text fileds(In short sentences, this is often convenient.).
But \<C-u\> is only not working(instead of setting it's Cmd+Del) in macOS.

## in cVim
In cVim(addin for Google Chrome), We can setting this by imap.

### Example
    imap <C-u> deteleToBegging

Thanks,

**Comment by bovine3dom** [comment]
On our help page (press F1), there's a link in the prose at the top to text editing commands. The documentation is a little hidden...

You want `bind --mode=insert <C-u> text.backward_kill_word`, and probably to repeat that for the input and ex modes.

**Comment by glacambre** [comment]
I think `bind --mode=insert <C-u> text.backward_kill_line` and `bind --mode=input <C-u> text.backward_kill_line` is what @nullplus is looking for.
Please note that lines are defined by newlines present in the text, not by "visual lines" (mostly because I couldn't find an easy way to implement it).

I'm closing this issue because I think it's solved, if I'm wrong please let us know/reopen this issue.

**Comment by nullplus** [comment]
I try `bind --mode=insert <C-u> text.backward_kill_line`... but it's not woring.

1. TRY1(fireforx is not restart)
   - `bind --mode=insert <C-u> text.backward_kill_line` in ex. mode.
   - check by `bind --mode=insert <C-u>`
   - tridactyl is displayed `<C-u> = text.backward_kill_line`
   - Page reload (I try on Google top page)
   - "gi" -> *anything type* -> "\<C-u\>" -> not woring

1. TRY2 (firefox is restarted)
   - `bind --mode=insert <C-u> text.backward_kill_line` in ex. mode.
   - check by `bind --mode=insert <C-u>`
   - tridactyl is displayed `<C-u> = text.backward_kill_line`
   - Restart Firefox.
   - "gi" -> *anything type* -> "\<C-u\>" -> not woring
 
What's wrong?
