### ISSUE TITLE
Eliminate similar looking characters from displaying in the hint mode

### ISSUE THREAD

**Issue by neshkeev** [tridactyl/tridactyl#1261]
*   Brief description of the problem:

When I see if there is a "Q" or "O" character in the hint mode, I cannot identify which one it it is, because they look similar.
![screenshot_2018-12-26 psytrance progressive goatrance dj mix 2017 - youtube](https://user-images.githubusercontent.com/4223091/50431968-c5c10000-08df-11e9-9c85-44effd0d38ed.png)

*   Steps to reproduce:

1. Open a page with lots of links on it (for example, YouTube)
2. Hit "f" or "F" to enter the hint mode
3. Locate links with "Q" or "O"

*   Tridactyl version (`:version`):
1.14.6-1.14.6
*   Firefox version (Top right menu > Help > About Firefox):
64.0
*   URL of the website the bug happens on:
https://www.youtube.com
*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
[config](https://gist.github.com/neshkeev/325751b2b1282ae97ad173aae7829ac3.js)
*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

*   Operating system: `Linux 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux`
*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
```
$ printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py
bash: ~/.local/share/tridactyl/native_main.py: No such file or directory
```

**Comment by glacambre** [comment]
You can use `:set hintchars abc` in order to only use `a`, `b` and `c` as hint characters (see `:help hintchars`), so this can already be done. I agree that the default font isn't great though (on top of the characters you mention, I also have trouble differentiating `i` from `l` from `j`) and this is why I changed the font in my config with [these two lines](https://github.com/glacambre/.dotfiles/blob/182682443cf45f296ee765ffa1ce9c02755571b5/default/.config/tridactyl/tridactylrc#L89-L90). It's pure CSS so you can do whatever you want. You can also use `:set hintuppercase false` in order to have hints be displayed in lowercase.

Since there are multiple solutions to your issue, I'm going to close it. Feel free to reopen it/let me know if there's anything else you need :)
