### ISSUE TITLE
Fix `editor` on codemirror etc

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1267]
GhostText claims it works with codemirror etc, so we should too. https://github.com/GhostText/GhostText

Edit: it looks like they just have a special workaround, https://github.com/GhostText/GhostText/blob/dc15bb2cb528dc48f69be80c9357690d40cbf849/browser/scripts/InputArea/CodeMirror.ts#L9 - which I think I'd like to avoid including. I'm tempted to leave `editor` a bit gimped, write a plugin for Tridactyl to talk to GhostText, and then recommend that people just use that.

**Comment by glacambre** [comment]
CodeMirror support is rather simple to implement. First, you need to find out if the textarea you're focusing [belongs to a CodeMirror element](https://github.com/glacambre/firenvim/blob/a86cbace5986c2fb063e8ec7a447f16b92d540ed/src/content.ts#L28-L30). Then you need to use [element.CodeMirror.getValue()](https://github.com/glacambre/firenvim/blob/a86cbace5986c2fb063e8ec7a447f16b92d540ed/src/page/functions.ts#L38-L41) in order to fetch its content and [element.CodeMirror.setValue()](https://github.com/glacambre/firenvim/blob/a86cbace5986c2fb063e8ec7a447f16b92d540ed/src/page/functions.ts#L80-L83) in order to set it. The hardest part of it is that everything has to be done [in the page's context](https://github.com/glacambre/firenvim/blob/a86cbace5986c2fb063e8ec7a447f16b92d540ed/src/page/functions.ts#L4-L33) rather than in the content script.

**Comment by bovine3dom** [comment]
Dumb perhaps foolproof workaround: rather than setting the text directly, copy it to clipboard, focus the element and then use `document.execCommand("paste")`.

A more user friendly workaround would store the value of the clipboard before writing and restore it after so it didn't confuse the users.


I suppose the problem then becomes how to clear the element if it already has text in it.

**Comment by bovine3dom** [comment]
@glacambre we may have already had this conversation but can't we just use the `wrappedJSObject` thingy https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts#accessing_page_script_objects_from_content_scripts ? so `element.wrappedJSObject.CodeMirror.setValue()`

**Comment by glacambre** [comment]
That's very cool and I think it would indeed work. However it's not cross-platform (I know Tridactyl doesn't care about that for now though ;) ) and I'm afraid Mozilla might want to take that away from us in manifest v3 (I don't have any reason to think this, I just feel like this is the kind of stuff they like to remove). But it certainly beats the method I currently use in Firenvim, which doesn't work on websites with very strict CSPs.
