### ISSUE TITLE
compiler/types/LiteralTypeType.js throws error on non-zero numbers if number is initally zero

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1281]
Minimal example:

add new setting,
```
blah: 0
```

to config.ts.

Try `:set blah 1`. 

Get error "Argument does not match expected value (0): 1".

**Comment by glacambre** [comment]
Works fine for me. What typescript version are you using? `$(npm bin)/tsc --version` returns `Version 3.1.6` on my end.

**Comment by bovine3dom** [comment]
oh, woops, I was actually using the syntax `blah: 0` rather than `blah = 0`. I have corrected the OP.

Are we abusing TypeScript in the rest of the config? I guess the `:` syntax means "It can be of this type", but because there's only one possible thing it can be, it has to be that, so it initialises it to that?

**Comment by glacambre** [comment]
>I have corrected the OP.

Then everything works as expected I think. `default_config` is a class so properties are initialized with `=` rather than `:` and `:` is used to specify types.

>Are we abusing TypeScript in the rest of the config?

I don't think so, we're always using `=` to define default config values and `:` only when we need to specify other values a setting can take.

**Comment by bovine3dom** [comment]
Yeah, you're right. I was just misreading the objects that live in the class.
