### ISSUE TITLE
tridactyl command is covered by browsers's loading information in status bar 

### ISSUE THREAD

**Issue by mabier** [tridactyl/tridactyl#1284]
It is really annoying to see the websites' loading information cover my tridactyl command in the lower left corner, in this situation I can't see what I are typing , because what I typed kept being covered by browser's loading information . 
![2019-01-19_19-01](https://user-images.githubusercontent.com/7421605/51426042-cf5c3000-1c1f-11e9-9f6b-bc8d1be405f2.png)

**Comment by bovine3dom** [comment]
You have two/three options currently - 

- `:colours quake` - places bar at the top (or `:colours shydactyl` for Vimium style)
- `:guiset hoverlink right` - puts the information while you hover over a URL on the right. Doesn't effect loading though.
- fiddle with userChrome.css

The only thing we can do by default is move the bar, but I don't want to do that. I'm happy to leave this issue open if there's some obvious solution that I'm missing.

**Comment by mabier** [comment]
found this link https://github.com/tridactyl/tridactyl/issues/40 ,but neither the tweak in userchrome.css , nor guiset hoverlink top-right works.

**Comment by glacambre** [comment]
You can add
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

statuspanel[type="overLink"],
#statuspanel[type="overLink"] {
  right: 0;
  display: inline;
}
```
to your `~/.mozilla/firefox/$yourprofile/chrome/userChrome.css` in order to get what `:guiset` would give you. If you feel like helping us debug this issue, could you go through the following steps and let us know what the results are?
- go to `about:debugging`
- find Tridactyl
- click on `Debug`, this should open Firefox's debugger
- in the leftmost column of the debugger select `background.js` under the `moz-extension://` item.
- then look for (with `<C-f>`) the text `function guiset_quiet`, there should be only one match
- Place a breakpoint on the first line, `if (!rule || !option)`
- In Tridactyl, run `:guiset hoverlink right`
Tridactyl should begin running the command and then stop once it reaches the breakpoint. When the breakpoint is reached, make sure the `Pause on exceptions` and `Pause on caught exceptions` checkboxes under the `breakpoints` menu of the rightmost column are checked and then press the `Resume` button (the top-right triangle button). Tridactyl will then run and stop a few times. Each time it stops, please write down the name of the function Tridactyl is currently in (you can find it under `Call stack`, in the rightmost column) and resume execution.

This should help us discover what the problem really is. Sorry there are this many complicated steps, this is something we can't automate :/

**Comment by mabier** [comment]
I found my directory path is  /home/MY_USERNAME/.mozilla/firefox/manjaro.default/chrome,which is different from your recommended directory. I added these lines like this, restart ,still nothing happened! 
clicked on Debug, no response, the button is gray !
![image](https://user-images.githubusercontent.com/7421605/51428074-7d74d380-1c3a-11e9-97c2-cf1f03d3df54.png)

**Comment by glacambre** [comment]
You probably need to enable addon debugging by clicking on the `Enable add-on debugging` checkbox at the top of `about:debugging`.

**Comment by mabier** [comment]
Remove it, but still no change.
![image](https://user-images.githubusercontent.com/7421605/51428306-32a88b00-1c3d-11e9-817a-e0d5c8147c7f.png)
yes, the debugging checkbox need to be clicked first !

**Comment by mabier** [comment]
![image](https://user-images.githubusercontent.com/7421605/51428616-a8622600-1c40-11e9-90d1-9d5ee985b272.png)
![image](https://user-images.githubusercontent.com/7421605/51428621-b3b55180-1c40-11e9-9cd2-1d971b7c278c.png)
![image](https://user-images.githubusercontent.com/7421605/51428625-bf087d00-1c40-11e9-8920-c48ca5fec155.png)
![image](https://user-images.githubusercontent.com/7421605/51428629-ca5ba880-1c40-11e9-9719-dc5d4cf45e78.png)
![image](https://user-images.githubusercontent.com/7421605/51428634-d47da700-1c40-11e9-8f9a-9243e862e8c6.png)

**Comment by glacambre** [comment]
What the value of `:get profiledir`? If it's `"auto"`, could you try manually setting it to your profile directory?

**Comment by mabier** [comment]
have changed my profiledir, restart , still no change .

![image](https://user-images.githubusercontent.com/7421605/51437202-ff660a80-1cd5-11e9-942f-94170daa984b.png)

**Comment by glacambre** [comment]
>still no change .

Do you mean that you tried to run `:guiset hoverlink right` after having changed your `profiledir` and that it still failed? If yes, could you run the following commands in a shell and let us know what the results are?

```sh
USERCHROMEORIG="$HOME/.mozilla/firefox/manjaro.default/chrome/userChrome.orig.css"
mv "$USERCHROMEORIG" "/tmp/cssorig"
COMMAND='{"cmd":"write","file":"'"$USERCHROMEORIG"'","content":"ok"}'
/usr/bin/printf "\\x$(echo "obase=16; ${#COMMAND}" | bc)\\0\\0\\0%s" "$COMMAND" | ~/.local/share/tridactyl/native_main.py
cat "$USERCHROMEORIG"
mv "/tmp/cssorig" "$USERCHROMEORIG"
```
If everything goes smoothly this should print `{"cmd": "write"}` and `ok`.

**Comment by mabier** [comment]
this is the result:
![image](https://user-images.githubusercontent.com/7421605/51479911-990ee400-1dca-11e9-959c-51c7d9293489.png)

**Comment by glacambre** [comment]
Are you sure you have read/write permissions for `~/.mozilla/firefox/manjaro.default/chrome/`? I find particularly strange the fact that you couldn't move your `userChrome.css` out of it.

**Comment by mabier** [comment]
my userChrome.css 's user and group are both root, then I changed them to mabier (which is my user account and the group I belong to). Restarted firefox, still didn't work. I noticed that the chrome directory is a link , I don't know if this is the culprit.
![image](https://user-images.githubusercontent.com/7421605/51538217-b35cc680-1e8b-11e9-9248-bce2176bfe9a.png)

**Comment by glacambre** [comment]
Ah, you distro probably replaced the default userchrome with one fitting the theme you chose. I'm not sure overwriting files belonging to root is something we want to do so we're probably not going to fix this issue.

Adding
```css
statuspanel[type="overLink"],
#statuspanel[type="overLink"] {
  right: 0 !important;
  display: inline !important;
}
```
To the very end of your userChrome.css might fix things. Otherwise, you'll have to find out what other CSS files your distro makes Firefox load and append this snippet to the last one being loaded.

**Comment by mabier** [comment]
Tried both method, didn't work. 
I will stick with theme quake now.

**Comment by mabier** [comment]
I think you misunderstand my intention. My problem is not to show link information at right instead of left when my mouse cursor points to a link , my problem is : when a website is in the process of opening, the snippet of website information will appear at the bottom left corner of the screen, then during the time period when this snippet is showing ,I can not input command with tridactyl with default color theme because the snippet at the bottom left corner will cover what I typed which is also located at the same (bottom left corner) area. In order to normally input tridactyl command , I have to wait for the disappearing of the overlapping snippet. You know, I don't want to wait although maybe the waiting time is not too long. You know what I mean ?

**Comment by glacambre** [comment]
Oh, you're right, I misunderstood what your problem was, sorry. My tests seem to indicate that removing the `[type="overLink"]` bit is enough to fix this issue. Could you try that and report back?

**Comment by bovine3dom** [comment]
Oh, wow, sorry, I hadn't been paying attention to this issue.

I did say right at the start

> :guiset hoverlink right - needs native messenger. Puts the information while you hover over a URL on the right. __Doesn't effect loading though.__

I think it would be quite reasonable to support this with `guiset`.

**Comment by mabier** [comment]
Ok, the issue raised by me here is solved sastifactionarily by removing "[type="overLink]" , thank you guys !

**Comment by mabier** [comment]
> 
> 
> What the value of `:get profiledir`? If it's `"auto"`, could you try manually setting it to your profile directory?

I encountered the similar issue under Window 10 recently, I tried lots of thing ,but nothing worked until I followed your advice of setting the profiledir manually to firefox's profile folder, everything is OK now, thanks again !!  ;-)
