### ISSUE TITLE
Search only opens new tabs or throws an error message.

### ISSUE THREAD

**Issue by kxxvii** [tridactyl/tridactyl#1332]
Seems like search only opens a new tab for me. Can't say that I have done anything fancy to provoke it. At first it threw me an error message. Two different ones and separate times. Can't remember exactly what it said, but it said something like "searchEngine not set". I have it set. The other complained about "browserBg.search undefined".

Tried setting different ones without much luck. Just using FF for search works just fine.

Tridactyl version: Tridactyl 1.14.8-43-g799f2d3

Some (maybe irrelevant) console output. Mindlessly copy/pasted:

```
background_controller:  TypeError: browserBg.search is undefined
Stack trace:
openInTab@moz-extension://65e92e7d-1c15-4b23-8872-75abf165a7cc/background.js:33633:11
tabopen/</<@moz-extension://65e92e7d-1c15-4b23-8872-75abf165a7cc/background.js:25754:109
background.js:32645:39
log/< moz-extension://65e92e7d-1c15-4b23-8872-75abf165a7cc/background.js:32645:39 acceptExCmd moz-extension://65e92e7d-1c15-4b23-8872-75abf165a7cc/background.js:28072:13
TypeError: localStorage is null[Learn More]  newtab.js:1303:1
updateChangelogStatus moz-extension://65e92e7d-1c15-4b23-8872-75abf165a7cc/newtab.js:1303:1
Error: Could not establish connection. Receiving end does not exist.  background.js:32660:36
```

**Comment by kxxvii** [comment]
First of all: Don't be sorry. You owe me nothing, haha. Secondly: 60.5.0esr (64-bit). On Debian Testing if that would make any difference.

**Comment by glacambre** [comment]
>Don't be sorry. You owe me nothing

Thanks. Still, it's not nice to have Tridactyl suddenly break and become useless, so I'm still sorry :p.

We recently modified the way `:open` and `:tabopen` handle queries in order to use newer APIs that enable interacting with the browser's search engine. These APIs aren't available in Firefox ESR and so we specified in the [extension manifest](https://github.com/tridactyl/tridactyl/blob/92f82016f21a63bf241a0b4c37c838b783560a8d/src/manifest.json#L67) that Tridactyl only supported firefox versions greater than or equal to 64.

This means that tridactyl shouldn't have updated for you and that there's probably a bug in Firefox. The only solutions I can suggest are to either install an older Tridactyl version (perhaps the one on addons.mozilla.org) or upgrade your Firefox (Debian has a package for the stable version of Firefox and if it isn't new enough you can also try to apt-pin the version from the unstable repos, although I doubt this is necessary).

If you decide to downgrade Tridactyl, you'll need to export your config and to re-import it in the stable version of Tridactyl. You can do this by opening Tridactyl's newtab, help or tutorial pages, opening the console (`<C-I>`), running `JSON.stringify(tri.config.get())` and copying the output. You can then uninstall the beta version of Tridactyl, install the stable one and run `let myConfig = JSON.parse($STRING_THAT_YOU_COPIED); Object.keys(myConfig).forEach(key => tri.config.set(key, myConfig[key]))` in the console in the newtab/help/tutorial pages in order to restore your config.

Making Tridactyl work when APIs aren't available is something we plan on doing someday (https://github.com/tridactyl/tridactyl/issues/1282, https://github.com/tridactyl/tridactyl/issues/854) but we're not there yet.

**Comment by kxxvii** [comment]
> Thanks. Still, it's not nice to have Tridactyl suddenly break and become useless, so I'm still sorry (I'm personally responsible for this bug) :p.

If you feel that strongly about it I won't argue with you, haha. Your support and explanation of the problem is appreciated. Thank you.

Anyway, I'm not married to 'firefox-esr', and I can't remember why I started using it. Wasn't even using the version in the Debian repos. Always went with mainline or beta before that. I suspect something I wanted to do with Firefox didn't work as I wanted it to, so I downgraded. I.e. can't have been that important.

Long(ish) story short: I switched back to mainline now. That solved my problems pretty quickly. :) I lean on Tridactyl for a lot of things nowadays so that particular decision was an easy one to make.

I had `:tabopen` opening dual tabs at first, but I suspect that might be something at my end (got a jungle of scripts and dot-files doing a couple of things for me when I used FF). Haven't happened again.

As far as I'm concerned you can close this. If I bump into more problems it's most likely not related to this one.

**Comment by glacambre** [comment]
>I had `:tabopen` opening dual tabs at first, but I suspect that might be something at my end

No, that's a Tridactyl https://github.com/tridactyl/tridactyl/issues/1237 (probably firefox https://github.com/tridactyl/tridactyl/issues/760#issuecomment-447642870 ) bug unfortunately :/.

**Comment by DarkStarSword** [comment]
FWIW this hit me as well, also running Firefox 60 ESR on Windows (I was on ESR to stay with Pentadactyl as long as possible, until Firefox forced an update on my anyway and I never noticed that it stayed on ESR).
