### ISSUE TITLE
# background_controller:  Error: An unexpected error occurred in Firefox 65

### ISSUE THREAD

**Issue by livnev** [tridactyl/tridactyl#1345]
*   Brief description of the problem:

Trying to enter the tridactyl mode with `:` results in the following message appearing in my input bar:

```
# background_controller:  Error: An unexpected error occurred
```

This is how it looks:

![screenshot127](https://user-images.githubusercontent.com/3964494/52534474-bbe14800-2d39-11e9-99db-39c2d0b36464.png)

If I delete the error message that appears and try to type something, it usually immediately appears again, so that I can't execute any commands. Note that I was also experiencing issues described in #1229 until I removed `guiset` commands from my `.tridactylrc` and deleted my `userChrome.css`.

*   Steps to reproduce:

    1.  Type `:`

*   Tridactyl version (`:version`):

`1.14.8-1.14.8`

*   Firefox version (Top right menu > Help > About Firefox):

`Firefox 65`

*   URL of the website the bug happens on:

everywhere

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/livnev/9935ccca5a8f5285ebeb6df6ecfd4e4b

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
set smoothscroll true

bind j scrollline 5
bind k scrollline -5

bind ? help

bind t tabnew
bind x tabclose

bind O fillcmdline tabopen

bind <C-v> scrollpage 0.5
bind <A-v> scrollpage -0.5
bind d scrollpage 1
bind u scrollpage -1

bind K tabnext_gt
bind J tabprev

bind <A-<> scrollto 0
bind <A->> scrollto 100

bind . viewsource

set searchengine duckduckgo

colors dark

set allowautofocus false

```

**Comment by livnev** [comment]
n.b. have tried installing a tridactyl beta: `1.14.8-64-gcd99fe7`, still the same issue.

**Comment by livnev** [comment]
I've also been able to narrow down exactly when the error appears: it's either when entering the mode when I press `:` or when already inside the command line and I press `SPACE`. I can successfully run commands provided I delete the initial error message and don't type `SPACE`. So it looks similar to #1167 but I don't get the same error message...

**Comment by glacambre** [comment]
Hi. I unfortunately can't reproduce this issue. Could you follow the following steps?
1) Open the tridactyl newtab page
2) Open Firefox's console with `<C-I>`, navigate to the `debugger` tab
3) Open Tridactyl's command line with `:` and remove the error message
4) In the debugger, enable `pause on exceptions` and `pause on caught exceptions` in the rightmost column
5) Press `<Space>` in Tridactyl's command line to trigger the bug. Execution should stop and a line should be highlighted in the central window.
6) The rightmost column should now have a `callstack` section. Write down each function name/filename/line number.
7) Resume execution by clicking on the `play` button at the top of the rightmost column. If execution is paused again, go back to 6).
8) Uncheck `pause on exceptions` and `pause on caught exceptions` in the rightmost column and close the debugger.

Knowing the call stacks should help us understand where this issue is coming from.

**Comment by livnev** [comment]
@glacambre  `<C-I>` opens something else, the web console is `<C-S-K>`.

I did this and found the following sequence of breakpoints:

![screenshot133](https://user-images.githubusercontent.com/3964494/52537522-b696f400-2d5f-11e9-8cbd-43db465a5ab7.png)
then
![screenshot134](https://user-images.githubusercontent.com/3964494/52537523-b8f94e00-2d5f-11e9-8694-9261f7de7923.png)
then
![screenshot135](https://user-images.githubusercontent.com/3964494/52537524-bac31180-2d5f-11e9-9420-f88dfc36b5ce.png)
then
![screenshot136](https://user-images.githubusercontent.com/3964494/52537525-bbf43e80-2d5f-11e9-9607-cc1fcfebe021.png)
then execution completed (with the error message vomited into the Tridactyl command line).

**Comment by glacambre** [comment]
Thanks. #1347 should make the command line usable again but it doesn't fix the underlying problem (browserBg.sessions.getRecentlyClosed() failing) which means you still can't get `:undo` completions.

Could you repeat the whole call-stack screenshotting procedure with the background process's console? You can find it by going to `about:debugging`, ticking the `enable extension debugging` checkbox, finding Tridactyl in the list of extensions and clicking on `Debug`.

**Comment by glacambre** [comment]
If you checked the `catch exceptions` checkboxes before opening Tridactyl's command line, the error you caught come from the library we're using to parse key events and aren't actually related to the issue you're experiencing, I should have made that more clear, sorry :(.

Could you repeat the process and make sure you're only checking the checkboxes after the command line has been open? This should ensure that you're only catching the errors that are thrown when you press `<Space>`. Sorry :(.

**Comment by livnev** [comment]
@glacambre sure thing: I open up the command line, get the error, delete the output, press `<Space>`, and get:

![screenshot149](https://user-images.githubusercontent.com/3964494/52564551-69b52b00-2dfc-11e9-9224-9388e6adf6e9.png)
then
![screenshot150](https://user-images.githubusercontent.com/3964494/52564580-78034700-2dfc-11e9-9286-25ca3aa5973f.png)
then
![screenshot151](https://user-images.githubusercontent.com/3964494/52564585-7afe3780-2dfc-11e9-82a3-f50c6ab16a6d.png)
then
![screenshot152](https://user-images.githubusercontent.com/3964494/52564590-7df92800-2dfc-11e9-867d-40c8b4f7dbf5.png)
then
![screenshot153](https://user-images.githubusercontent.com/3964494/52564594-80f41880-2dfc-11e9-8dcd-9edd52eee83d.png)

and that's it.

**Comment by glacambre** [comment]
Thanks a lot for taking the time to do this. This call stack doesn't make any sense though. Looking at [Firefox's source code](https://dxr.mozilla.org/mozilla-central/rev/c2593a3058afdfeaac5c990e18794ee8257afe99/toolkit/components/extensions/docs/functions.rst#125) it seems that this might be a Firefox bug rather than a Tridactyl one. Can you reproduce this bug on a clean profile? If not, could you make a copy of your current profile, anonymize it (`<C-S-Del>`, select everything, delete and also go through the `privacy & security` settings in `about:preferences` to make sure there's nothing left), see if you can still reproduce the bug and if you can, send your profile to me (you can get my email address on my github profile I believe)? I completely understand if you'd rather not though so don't feel forced :).

**Comment by livnev** [comment]
@glacambre Mysteriously I'm no longer able to reproduce this bug. And it's not because your band-aid fix got merged, I stopped being able to reproduce it before that. If it returns I'll continue the investigation. Thanks for your help.

**Comment by glacambre** [comment]
Thank you for letting us know :)

**Comment by mgiorgino** [comment]
I'm also experiencing this problem in Firefox 65 (65.0.2). I'm running firefox from a snap (https://snapcraft.io/firefox) on Debian (Linux 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux). Installing the beta fixes the problem (but doesn't fix the underlying problem, as you said).
