### ISSUE TITLE
Strange find behaviour on Google search pages

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#1441]
Hi,

perhaps someone can replicate this:

1. visit `https://www.google.com/search?q=test`
2. then `:find test`
3. nothing happens?

Thanks

**Comment by cmcaine** [comment]
Happens for me too.

Our find mode is pretty broken (last time Olie and I tried together it was
hard to get anything working fast enough; Olie and others seem to have
tried again since then, but I don't know their results).

If you unbind / then you'll use the firefox search instead. Ctrl-g and
Ctrl-G are forwards and back.
