### ISSUE TITLE
[Feature Request] Keybinding for opening previous page in new tab

### ISSUE THREAD

**Issue by adamoudad** [tridactyl/tridactyl#1503]
I know there are several keybindings like F for opening in new tabs, but I sometimes forget to do so, and think a keybinding for opening previous page in new tab would be great for navigation.

Cheers.

**Comment by bovine3dom** [comment]
`composite js document.location.href | tabopen -b; back` should work. See `help bind` for how to bind it.

**Comment by adamoudad** [comment]
It seems `composite js document.location.href | tabopen -b; back` opens a new tab with the previous page, but also goes back to the previous page in the current page.

I am experimenting but cant find the right command..

I am basically searching for a command with the same effect as middle-click on the "Go back one page" button.

**Comment by glacambre** [comment]
`composite js document.location.href | jsb -p tri.excmds.back().then(_ => tri.excmds.tabopen(JS_ARG))` might work better.

We can't implement the exact behavior you need (opening the previous website in a new tab) because Firefox doesn't have an API that enables querying a tab's history. We could probably try to keep track of this information ourselves but there's a ton of edge cases to consider (user going back in history, page deciding to go back in history, redirects, user going forward in history but not visiting a new page…) so it's rather complicated. I do plan on implementing that someday though.

**Comment by bovine3dom** [comment]
Try adding `sleep 100` between tabopen and back. It's my usual approach to fixing these race conditions without having to apply my brain too much :)

**Comment by adamoudad** [comment]
Ok sorry, actually `composite js document.location.href | tabopen -b; back` opens a new tab with current page in background and goes back in history, so it solves my problem.

With `composite js document.location.href | jsb -p tri.excmds.back().then(_ => tri.excmds.tabopen(JS_ARG))` focus on the newly opened tab, that's interesting too, thanks !

Indeed it would be great to keep track of history in the new tab though.

**Comment by bovine3dom** [comment]
Ah, in that case, do `composite tabduplicate; back` :)
