### ISSUE TITLE
`repeat` seems to be broken

### ISSUE THREAD

**Issue by gsbabil** [tridactyl/tridactyl#1538]
### Description of the problem

- `repeat` command does not seem to work on Tridactyl version `1.14.10-212-g70fa456`

### Steps to reproduce

- Navigate to `https://github.com/tridactyl/tridactyl/issues/1537`
- Perform `urlincrement` or `urldecrement` operation e.g. using `C-a` or `C-x` key
- Perform `repeat` operation e.g. using `.` key

   - **_Nothing happens on `repeat`_**

### Software Versions

- Tridactyl version : `1.14.10-212-g70fa456`
- Firefox version   : `Developer Edition 67.0b18 (64-bit)`

**Comment by bovine3dom** [comment]
Also:

1. `d`
2. `.`
3. `# controller while accepting: Could not find type information for excmd`

**Comment by glacambre** [comment]
The `# controller while accepting: Could not find type information for excmd` error appears because [controller.last_ex_str](https://github.com/tridactyl/tridactyl/blob/53e4a4ec4b94d69e14397835ef1b47e3cdfd5c1a/src/excmds.ts#L2649) is an empty string.

**Comment by gsbabil** [comment]
The issue isn't correctly fixed, not at least in `1.17.1pre3643-09f6831`.

For example, if you press `C-a` or `C-x` for URL increment/decrement, and then press `.` to repeat, the correct URL increment/decrement steps aren't repeated.

To elaborate further:

- Go to https://news.ycombinator.com/item?id=22464765
- Press `:version`
- Press `<ESC>`
- Press `C-a`; Browser navigates to https://news.ycombinator.com/item?id=22464766
- Press `.` (to repeat the previous `C-a` step) - nothing happens.

Hope this helps. Thanks.

**Comment by bovine3dom** [comment]
It works flawlessly in a temporary profile for me.

In a real profile with lots of tabs it works sometimes. 

I think there are two issues here:

- our locks library tries to send messages to tabs that Tridactyl isn't running on. We should probably switch to a port based method where tabs actively ask to subscribe to the locks.

- it's a bit daft sending messages to every tab to update the last_ex_str every time we run an ex-command. `state.ts` is only rarely used so we should probably instead store it in the background in memory, adding latency to read-time rather than write-time

**Comment by bovine3dom** [comment]
This appears to be fixed for me after 9e750f6
