### ISSUE TITLE
Can't type numbers

### ISSUE THREAD

**Issue by LinuxMercedes** [tridactyl/tridactyl#1649]
*   Brief description of the problem: Can't type numbers (1234567890) in text boxes.

    This is a new problem as of today; both firefox and tridactyl recently updated so I'm not sure which of these things is exactly responsible

*   Tridactyl version (`:version`): 1.15.0pre2873-1da17bf

*   Firefox version (Top right menu > Help > About Firefox): 66.0.5

*   URL of the website the bug happens on: most websites, including google.com search bar or the textbox on github I'm typing this in

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): https://s3.amazonaws.com/raw.paste.esk.io/Azou1Rcfcm?versionId=Mnp2F2OWDOQzBGR5UZ32SU0OLZYBcSSi

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): N/A

**Comment by antonva** [comment]
Hi, 

There was a regression on our beta branch  a couple of days ago, this has been fixed.
As of at least version: `1.15.0pre2877-49f9263` there are no problems wrt numbers that I can see.

In order to make sure you're on the latest version, you can grab `tridactyl-latest.xpi` from the [beta builds](https://tridactyl.cmcaine.co.uk/betas/?sort=time&order=desc).

**Comment by bovine3dom** [comment]
Sorry about this. As azk says, it is fixed in the latest betas. Thanks for reporting.

**Comment by cmcaine** [comment]
This was my fault - I still have commit access to the repo and pushed some untested code. I'll try to remember not to do that again.

**Comment by LinuxMercedes** [comment]
thanks!

**Comment by LinuxMercedes** [comment]
and thank you all for making such a useful plugin -- I really appreciate the work that goes into this!
