### ISSUE TITLE
tabopen always opens newtab

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [tridactyl/tridactyl#1746]
Tridactyl version: 1.16.2pre2999-95db0a8
Firefox version: Mozilla Firefox 68.0.1
Operating system: archlinux

No matter how I call `:tabopen some.url`, I always get redirected to `newtab` (the url in Tridactyl config). If `newtab` isn’t set, then I’m redirected to Tridactyl’s default new tab page.

I first noticed this because calling `:help` on any page (except help pages) creates a new tab, displays Tridactyl’s new tab page and stops there.

It is probably linked to #1237 and [#760](https://github.com/tridactyl/tridactyl/issues/760#issuecomment-447642870), if I understood correctly these issues.

**Comment by glacambre** [comment]
That's a weird issue. Could you update your Tridactyl to the latest version (currently pre3023-858cc67), open the Tridactyl newtab page, type `:tabopen some.url` (without pressing `<CR>`), open firefox's debugger (`<CS-k>`, click on the "Debugger" tab), tick the `Pause on exceptions` and `Pause on caught exceptions` checkboxes and then press `<CR>` in Tridactyl's command line?

Tridactyl will stop executing in various places. Each time it does so, please write down the error message and its call stack (both available in the rightmost column) and then upload the whole thing here.

**Comment by Druidefix** [comment]
Tridactly version: 1.16.2pre3025
Firefox version: 68.0 (64-bit)
Operating System: Ubuntu 18.04

I have a similar or the same problem: Using `t some.url` just opens a new tab instead of opening the url directly. Additionally, it was previously possible to search with google directly by `t searchkeyword` which also just opens the default tridactly new tab page.

I tried to follow your guide, but it did not stop at _various places_, only once.

https://ibb.co/k4vYjjb

**Comment by glacambre** [comment]
Huh. Could you place breakpoints on the tabopen function? In order to do this, go to `about:debugging`, make sure the `Enable addon debugging` checkbox at the top of the page is checked and then look for the `Tridactyl` section and click on `Debug`. This should open a new debugger window. Make sure pausing on exceptions and caught exceptions is enabled and then try running tabopen again. This should give us a better error message.

**Comment by Druidefix** [comment]
Unfortunately, there is not much more to see. Could it be possible that it is checked if the first word is a search engine? And if not, this leads to an error?

https://ibb.co/CQPy3Z2

**Comment by schyzophrene-asynchrone** [comment]
Already reported in #1728 actually (second point of first message).

**Comment by schyzophrene-asynchrone** [comment]
`:guiset navbar always` and `:restart` corrects it.
`:guiset gui none` and `:restart` doesn’t recreates the issue.

**Comment by schyzophrene-asynchrone** [comment]
As far as I’m concerned, you may close the issue, or link it to #1728 (since it seems it’s only a special case of it).

**Comment by bovine3dom** [comment]
That's because `gui none` doesn't set `navbar none`.
