### ISSUE TITLE
Remove fixamo

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1773]
Firefox have got in touch to say they'd like to see fixamo removed as they believe it makes Firefox insecure.

A separate but related issue: they would also like us to revert the changes we made to existing user.js but I firmly believe that doing that unprompted would be a breach of trust of our users, not to mention that I do not have the time to do work out how to remove only those lines from user.js (and God knows if we were the ones who made that change).

**Comment by arcnmx** [comment]
Well maybe they should offer an extension whitelist pref rather than a domain blacklist so the only solution available to tridactyl here isn't the current shotgun approach. Tangentially related question (and not suggesting this be done automatically but I'm curious): is it possible to install tridactyl locally with the `mozillaAddons` permission to accomplish something similar?

**Comment by bovine3dom** [comment]
The first bit sounds sensible but I wouldn't hold my breath. If you want any chance of it happening, I would suggest filing a bug on bugzilla.

The second, I have no idea, but that would be cool as it would also let it work on PDFs (although just bundling pdf.js would be easier #541).

**Comment by glacambre** [comment]
Removing `:fixamo` isn't a big deal but when you say they want us to revert changes we made to existing user.js, do you know if it means they're also asking us to remove `:setpref`?
