### ISSUE TITLE
`help nmaps` doesn't take you to nmaps

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#1780]
Tridactyl version: 1.16.2pre3033-e6d5416
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

`help imaps` works as expected, though.

**Comment by glacambre** [comment]
The anchor is named `nmaps-1` instead of just `nmaps`. This is rather weird because there isn't any `nmaps-0` or `nmaps-2`.

**Comment by anoopelias** [comment]
> The anchor is named `nmaps-1` instead of just `nmaps`. This is rather weird because there isn't any `nmaps-0` or `nmaps-2`.

But there _is_ a `keytranslatemodes.nmaps` present. `imaps` works since (I think) it is processed in alphabetic order : `imaps`, `keytranslatemodes` and then `nmaps`. Interestingly, there _is_ a `keytranslatemodes.imaps-1` as well.

This is a probably a problem with `getUrl` function in `DefaultTheme.ts` from typedoc repo [here](https://github.com/TypeStrong/typedoc/blob/8ace3f5bf7da45294223e78c33932916df60b6e8/src/lib/output/themes/DefaultTheme.ts#L349). Typedoc is finding a unique anchor before prepending `keytranslatemodes`.

**Comment by bovine3dom** [comment]
Thanks for looking into it! We're already running our own fork of that as we had some trouble getting a PR merged - https://github.com/tridactyl/typedoc-default-themes - so if you spot an easy fix it would be best for us if you make a PR directly to us (but do contribute it upstream, too :) ).

**Comment by bovine3dom** [comment]
Can no longer reproduce
