### ISSUE TITLE
Binding keys to arrows

### ISSUE THREAD

**Issue by avalonv** [tridactyl/tridactyl#1801]
Before installing tridactyl pressing tab in a input box like the "Search or jump to..." on github (upper left) would move to the next element/suggestion.
Tridactyl changed this to `<ArrowUp>/<ArrowDown>`, but I would like to use `<A-k>/<A-j>` instead, how can I achieve this?

**Comment by glacambre** [comment]
The mode that changes how `<Tab>` behaves after you use `gi` is input mode (not to be confused with insert mode, which is used when you click directly on an input field). In order to know what `<Tab>` is bound to in input mode, you can use `:bind --mode=input <Tab>`. You can then bind different keys to the same command with `:bind`.

I'm not sure we bind anything to `<ArrowUp>/<ArrowDown>` by default, so what you're seeing probably is firefox's default behavior. You can probably reimplement that behavior by using `:js` and taking a look at how [focusinput](https://github.com/tridactyl/tridactyl/blob/132e385a7667224f625adeb91fee06bcecddd919/src/excmds.ts#L1846-L1912) works though.

**Comment by avalonv** [comment]
I see thanks. You can close this issue
