### ISSUE TITLE
How to load unsigned extensions?

### ISSUE THREAD

**Issue by alexherbo2** [tridactyl/tridactyl#1927]
Hello Tridactyl users :hatched_chick:

I would like to know if you know a way to load unsigned extensions without requiring a developer or unbranded version of Firefox.

**Comment by bovine3dom** [comment]
To load one temporarily go to about:debugging, "This Firefox" and click "Load temporary add-on from file".

More permanently: many (most?) Linux distributions allow unsigned extensions to be placed in /usr/lib/firefox/browser/extensions/ and they will automatically be loaded, provided they have valid names (e.g. dodgy@unsignedextension.com.xpi).

Otherwise, it is probably possible to patch the "omni.ja" file that contains Firefox's JS code. I wouldn't recommend this as it would be very brittle, requiring re-running every time Firefox was updated.

**Comment by alexherbo2** [comment]
I’m looking for a better workflow, because I noticed only developer and unbranded versions of Firefox could change `xpinstall.signatures.required` option.

For installing I generate an unsigned `package.zip` file and tell users to:

```
Open about:config, change xpinstall.signatures.required to false.
Open about:addons ❯ Extensions, click [Install add-on from file] and select the package file: /path/to/package.zip.
```

About the permanent method, you tell me all I have to do is rename `package.zip` to `name@mozilla.org.xpi` and move the file to `/usr/lib/firefox/browser/extensions` directory?

I’m also wondering if `browser_specific_settings` and `xpinstall.signatures.required` will still be necessary.

`manifest.json`

``` json
{
  "browser_specific_settings": {
    "gecko": {
      "id": "name@mozilla.org"
    }
  }
}
```

If anything, what do you think would be the best?

**Comment by bovine3dom** [comment]
> what do you think would be best?

Get your extension signed by Mozilla, then anyone can install your stuff :)

You can self-host add-ons that are signed by Mozilla and have them signed in an automated fashion. Add-ons hosted on the AMO generally need to have their source code uploaded on an extra (really annoying) manual step. Our script for signing is here https://github.com/tridactyl/tridactyl/blob/master/scripts/sign and the script for our build bot is here https://github.com/tridactyl/buildbot/blob/master/autobuild.sh - you could definitely do this with a free CI service and GitHub actions/releases but that's all a bit new-fangled for us.

> About the permanent method, you tell me all I have to do is rename package.zip to name@mozilla.org.xpi and move the file to /usr/lib/firefox/browser/extensions directory?

Yup.

> I’m also wondering if browser_specific_settings and xpinstall.signatures.required will still be necessary.

The latter - no. It's turned on at Firefox-compile time so that distributions can distribute extensions through their repositories (e.g. firefox-tridactyl in the AUR) without having to ask Mozilla if that's OK first.

I hadn't heard of the former but we do something similar - 

https://github.com/tridactyl/tridactyl/blob/master/scripts/install.sh


Our build scripts are really quite ugly but I hope you get the gist.

**Comment by mozbugbox** [comment]
The ESR version of Firefox can also use unsigned extension. 

https://extensionworkshop.com/documentation/enterprise/enterprise-distribution/#signed-vs-unsigned
