### ISSUE TITLE
Firefox 70 does not install xpis from links any more

### ISSUE THREAD

**Issue by cmcaine** [tridactyl/tridactyl#2006]
In the readme, we tell people to just click the link to install tridactyl. Now you have to download tridactyl, go to addons, install from file and then select the xpi from the filesystem.

We should have a check around and see if we can get the old behaviour somehow. If not, we should update the readme.

**Comment by cmcaine** [comment]
Tested on windows and manjaro.

**Comment by alerque** [comment]
I'm pretty sure even if you check around and find a way to get the old behavior, its not worth presenting that as an option. This "feature" was removed on purpose and any workarounds to make the old behavior will likely be squashed as bugs in future releases. In this case I think documenting the Mozilla recommended procedure as the "right" one is the best way to not have to keep changing this as workarounds come and go.

I'm not saying this because I like the extra steps (I'm pretty frustrated with Mozilla's not letting me do what I want with _my_ browser), just because I think its the most pragmatic way to document the installation.

**Comment by cmcaine** [comment]
Yeah, I meant more like "can we host the file differently to get the old
behaviour" not "can we find some about:config values to tweak"

**Comment by bovine3dom** [comment]
For me, clicking our link on readme.md and then choosing "open with: Firefox" (which is the default) in the download prompt works fine.

Can you confirm that you don't get this option?

**Comment by cmcaine** [comment]
Confirmed. If I do that it just offers to download it again.

**Comment by bovine3dom** [comment]
Documented this in the readme. It's more user friendly this way
