### ISSUE TITLE
Hints are slow on large pages

### ISSUE THREAD

**Issue by glacambre** [tridactyl/tridactyl#2155]
Tridactyl version: 1.17.1pre3519-041ad83
Firefox version: Mozilla Firefox 72.0.2
Operating system: linux

Reproducer:
- Open https://github.com/llvm/llvm-project/commit/372bfc65deb
- Wait for it to load (you'll know when this happens by pressing G and waiting for the scrollbar to stop moving)
- Go back to the top of the page
- Press `f`

**Comment by mozbugbox** [comment]
In the `content/hinting.ts`,  it seems that a `Hint` object was created for every hintable element in all the hint builders, whether or not the element was visible. Too many useless elements insert into a page will contribute to the slow down.

https://github.com/tridactyl/tridactyl/blob/6cc1094a81bf1d049edad95eadb4f78a4f8e6c2d/src/content/hinting.ts#L551-L555

Maybe before creating a hint, check its visibility first.

**Comment by mozbugbox** [comment]
Ok, I was wrong, it filtered by visibility already.

https://github.com/tridactyl/tridactyl/blob/6cc1094a81bf1d049edad95eadb4f78a4f8e6c2d/src/content/hinting.ts#L749-L756

**Comment by mozbugbox** [comment]
By adding some `console.time/timeEnd()` calls in the `hintable()` function, it surprised me that the most time was spent on the `unique(elems)` call. Since the `DOM.hintworthy_js_elems` was cached alone the page loading, that one took no time. 

It seems that make `hintworthy_js_elems` a `Set` and remove the `unique` call will speed up a lot with the price of slower page load.

Maybe somehow the `getElementBySelector()` can be cached too for `HINTTAGS_selectors` along with a Mutation listener.

**Comment by glacambre** [comment]
Thanks for fixing this, @mozbugbox!
