### ISSUE TITLE
C-a doesn't work in ex

### ISSUE THREAD

**Issue by hppavilion1** [tridactyl/tridactyl#2285]
Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 74.0
Operating system: win

It's possible that this is working as intended. I browsed through the issues a bit to see if it's already been brought up, but I couldn't find anything—however, it's possible this is due to poor choice of search terms.

When using `ex`, if I hit `control-A`, the cursor is returned to the beginning of the line. The expected behavior is that it should select the entire line (either keeping the cursor in place, moving it to the beginning of the line, or moving it to the end of the line), allowing the user to quickly delete a command and replace it (so enter a command → decide it sucks → C-a → whole line is selected → begin typing replacement command, clobbering the old one in the process)

Steps to reproduce:

1. Open `ex`
2. Enter any text
3. Hit C-a on your keyboard
4. Instead of selecting the entered text, your cursor has been moved to the beginning

**Comment by glacambre** [comment]
Yes, this is indeed the expected behavior. This default binding was added at the very beginning of Tridactyl and it is now too late to remove it. There are two solutions though:

If the reason you want to select everything is that you want to delete everything, use `<C-u>` to delete everything from the beginning of the line to the cursor and use `<C-k>` to delete everything from the cursor to the end of the line.

If you'd really prefer to use `<C-a>` to do this, you can unbind it like this: `:unbind --mode=ex <C-a>`. This will let you select text with `<C-a>` again.

**Comment by bovine3dom** [comment]
> it is now too late to remove it

As with #1433, we could remove it but "grandfather" all current users so that they keep the binds.

**Comment by glacambre** [comment]
I don't know. Grandfathering with config updaters would be confusing I think since they are run every time `:sanitize` is used. This would result in the following situation
- Use the defaults (`<C-a>` selects)
- Change something
- Be unhappy with it, run `:sanitize` to get back to defaults
- Config updater runs, adds the `<C-a>` binding
- Now you're back to a default config, except it's not default because `<C-a>` moves to the beginning of the line

**Comment by bovine3dom** [comment]
Oh, I thought we had started updating https://github.com/tridactyl/tridactyl/blob/14501f71d5ab63f71c6697702efe9721f250c565/src/lib/config.ts#L69 to the max config version. Surely it doesn't make any sense to keep it at 0? We should copy from default if user doesn't have a config version set (i.e. on first run), so all subsequent updaters will run in the future.

**Comment by bovine3dom** [comment]
I removed this bind a few days ago due to a popular uprising (2 people asked me to)
