### ISSUE TITLE
Update `tabprev` for FF68

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#2441]
The bug referred to in https://github.com/tridactyl/tridactyl/blob/af90d4cec255a4d20f8e6ec0e2bf6929691d581b/src/excmds.ts#L2093

was fixed in FF68, which is the minimum version supported by Tridactyl. Presumably there is some code we can tidy up here.

I'm not sure what the original bug was so I am reluctant to try to fix it myself. @glacambre do you remember? A mere two years ago :)

**Comment by glacambre** [comment]
The problem was that you could get in situations where there would be 
"holes" in your tab indexes and if you selected them, Tridactyl would cry.

I believe this code has since been reused to handle hidden tabs (so that 
tabnext doesn't select a hidden tab) and thus should stay. The comment 
should go though.
