### ISSUE TITLE
Tridactyl ignores nohup.

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#2468]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 77.0.1
Operating system: linux

Result of echo PATH: /home/simon/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl 

Result of Unix Command: {"cmd": "run", "content": "/home/simon/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/simon/.fzf/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n", "code": 0}% 

I was trying to use nohup to stop mpv instances from closing when Firefox closes, but mpv closes regardless.

Steps to reproduce:
1. Run mpv with nohup inside tridactyl 
For example this command: 'bind V composite get_current_url | js -p tri.excmds.shellescape(JS_ARG).then(url => tri.excmds.exclaim_quiet('nohup mpv ' + url))'
2. Close firefox.

I also tried variations of this theme such as writing a wrapper script for mpv trapping the signals, still no luck.

What does seem to work is running mpv inside a tmux session, but I would rather not do that if I don't have to.

BTW, tridactyl is awesome, keep up the good work :)

**Comment by saulrh** [comment]
Well, the native script uses python's `subprocess.Popen` with `shell=True`, which means the command is running underneath an invocation of `sh`. So I think `nohup` *should* be working. I wouldn't be too surprised if Firefox is aggressively killing descendant processes before it exits. In this case, `tmux` would be working because `tmux` maintains a persistent server process, all invocations of `tmux` are thin clients of this server process, and your `mpv` is being executed as a descendant of the server process and is completely unrelated to Firefox in the process tree. Try taking a look at `pgrep 'tmux|firefox' | xargs -n 1 pstree`.

**Comment by glacambre** [comment]
@simonhughcom simply double-forking works for me, e.g. `! xcalc &` will make xcalc survive firefox.
