### ISSUE TITLE
Feature Request: Combine more hint parameters, especially with -W.

### ISSUE THREAD

**Issue by simonhughcom** [tridactyl/tridactyl#2469]
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 77.0.1
Operating system: linux

It would be nice if you could combine the -J and -c parameter with other parameters such as -W (Or maybe you can and I just can't figure it out).

For example, you could do something like 'hint -Jc .someclass > a -W excmd'.

The reason why I want to use it is to have better hint suggestions on youtube for opening in mpv.

**Comment by bovine3dom** [comment]
We need a proper arg parser to do this properly. I think this is coming in #789, but it might be a very long time before that happens.

I think you can do what you want with `-pipe`, though, e.g.

`composite hint -Jpipe .someclass>a href | [excmd]`.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/a3691fc394fdcc554995b21e7d81044d28635110/src/excmds.ts#L3834 it does already try to communicate that - how could we make it clearer?

**Comment by simonhughcom** [comment]
Stating it more explicitly such as:
"-pipe css-selector key e.g, -pipe a href returns the key matching the css selector. Only makes sense with composite, e.g, composite hint -pipe .someclass > a textContent | yank. If you don't select a hint (i.e. press ), will return an empty string. Can be used similar to '-c' when similar precision is required but do not wish to open the link."
Or something along those lines.

I guess what was a little confusing is the 'selector' bit, I did not realize it meant css selector. 

I subscribe to the "Make it as explicit, so a 5 year old can get it" philosophy when it comes to documentation.

**Comment by bovine3dom** [comment]
Yeah, `-pipe` was added before most of the other options which is why it doesn't make much sense : )

**Comment by hejops** [comment]
Tried writing the following binding, but I'm not sure I got the syntax right, since mpv doesn't seem to be called. As an example, [this page](https://www.youtube.com/channel/UCzbu7dycxyeNwHrTlZ1TkAA/videos) has only one instance of the element.

`bindurl ^https://www.youtube.com/channel f composite hint -Jcpipe .yt-thumb-default | mpvsafe`

**Comment by bovine3dom** [comment]
I think there's two things wrong there:

- `pipe` takes two arguments, `selector` and `key`. You've only passed it the selector; you need to provide the name of the key belonging to the element that you want to pass to the next command. 99% of the time this is just `href`.

- I don't think your selector is right, it doesn't seem to return any elements. The easiest way to debug this is to open the web console - ctrl-shift-k - and use `document.querySelectorAll("[selector]")` to see which elements match your selector.

**Comment by hejops** [comment]
Sorry to reopen this; I've corrected the selector, and can confirm that the following 2 bindings work (the first should select the only available hint on this [example](https://www.youtube.com/channel/UCzbu7dycxyeNwHrTlZ1TkAA/videos) page):
`bindurl ^https://www.youtube.com/channel f hint -Jc span.yt-thumb-default`
`bindurl ^https://www.youtube.com/channel f hint -W mpvsafe`

But not when combined:
`bindurl ^https://www.youtube.com/channel f composite hint -Jpipe span.yt-thumb-default href | mpvsafe`

**Comment by bovine3dom** [comment]
`hint -Jc span.yt-thumb-default` doesn't select anything on that page for me.

`document.querySelectorAll("span.yt-thumb-default")` in the web console is an empty list.

**Comment by hejops** [comment]
Hmm, might have to do with YouTube on my end (I'm using the old UI). Would `hint -Jc [src^="https://i.ytimg.com/"]` work?

**Comment by bovine3dom** [comment]
Yeah, that works fine, e.g. `composite hint -Jpipe [src^="https://i.ytimg.com/"] src | fillcmdline`.

I suspect your issue is that you're trying to get the video link on that element which doesn't exist. MDN has a good page on CSS selectors: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

The reason the normal hint mode works on it is because we fire a fake mouse click on it which triggers a JavaScript event which takes you to the page.

`document.querySelectorAll('[src^="https://i.ytimg.com/"]')[0].href` needs to be a link to the video.

E.g. `document.querySelectorAll('a#thumbnail')[0].href` works fine for me.

**Comment by hejops** [comment]
Ah, I see. Many thanks for the clarification!
