### ISSUE TITLE
can't copy via link-hint with ;y on "source" button of pleroma-fe, get "undefined" on clipboard

### ISSUE THREAD

**Issue by Soundtoxin** [tridactyl/tridactyl#2635]
Tridactyl version: 1.19.1pre4277-b40c0ea
Firefox version: GNU IceCat 68.10.0
Operating system: linux

*   Brief description of the problem:
Copying the link of the "source" button puts "undefined" on my clipboard instead of the link.

*   Steps to reproduce:

1. open website
2. press ;y to open link hint copy mode
3. select the hint by the button with a diagonal arrow (labeled "source" if you hover over it)
4. paste your clipboard somewhere

(if you right click the button and hit copy link location you'll see what you should get)

*   URL of the website the bug happens on:
https://weeaboo.space/
also affects other instances like https://kawen.space/

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/Soundtoxin/615d9bc4a0b5f1cf224c3fbdc22f76cf

**Comment by bovine3dom** [comment]
That's curious. The hint is on the `<i` tag rather than the `<a` tag that encloses it.

**Comment by Rummskartoffel** [comment]
The `<i>` has a class called `button-icon`. If you remove that, hinting works correctly. Seems like classes containing "button" are favoured over `<a>`.

**Comment by bovine3dom** [comment]
must be from here https://github.com/tridactyl/tridactyl/blob/7b709264b5eeea6b1089714bf1e4370a6c42d935/src/lib/dom.ts#L607

**Comment by Rummskartoffel** [comment]
I investigated a bit more and I only just now noticed that the hint is very much there, it's just a bit misplaced. At first, hints for the `<i>` and the `<a>` are placed on top of each other, and `HintState.deOverlap()` then moves the `<a>`'s hint from on top of the arrow icon to roughly below the plus icon. So the problem here is not that the hint is missing, but that it doesn't indicate what it belongs to.
