### ISSUE TITLE
Add numbers for repeating <n> times the command.

### ISSUE THREAD

**Issue by plague-spreader** [tridactyl/tridactyl#269]
I would really like if you could implement numeric arguments to commands. For instance, in Vimperator pressing 3gt it would go three tabs forward, cycling to the first tab if the last one is reached.

**Comment by antonva** [comment]
This has already been implemented in at least a handful of commands ('gu' for example). I'll take a stab at implementing gt in this manner. @cmcaine thoughts on compiling a list of commands that should accept numeric arguments?

**Comment by cmcaine** [comment]
The current interpretation is that a number before a map is inserted after
the last argument of the bind. We will have a better system eventually.
@Koushien was working on it.

3gt turns into `tabnext_gt 3` which means change to the third tab. If you
want 3gt to take you forward three tabs you need to rebind gt to `tabnext`.

Default behaviour matches vim.

**Comment by cmcaine** [comment]
@antonva If you want to take a crack at doing it better the design that Koushien and I came up with was:

1. All commands are changed to receive an object as their first arg. For now this object will just have an optional key 'count', in future it may be used to send options (e.g. `hint -b` -> `hint({background: true})`).
2. The parser's handling of counts is changed. In particular, the exmode parser needs to accept an exstr and a count, rather than just an exstr.

This would allow us to apply counts to binds that already have a numerical argument, e.g. if `j -> scrollline 10`, then `10j -> scrollline 10 10` at the moment, but with this change the `scrollline` implementation can choose what to do if it receives both a count and a first argument.

If you think you've come up with a better design, please feel free to try it out and discuss it in chat. This isn't set in stone.

**Comment by Koushien** [comment]
@plague-spreader Is that a setting in Vimperator? It's definitely not default in latest and `:help gt` pulls up the following.
```
            Go to the next tab. Cycles to the first tab when the last is selected.
            If [count] is specified go to the [count]th tab.
```

In any case, it might be worth addressing this in the readme since, while most users probably come with experience in Vim, `tabnext` is a bit of an exception in terms of grammar with count. Something to the effect of

```
- How can I make gt cycle n times?
Enter the command `bind gt tabnext`. To restore default Vim-like behavior enter `bind gt tabnext_gt`.
```

FYI I resumed config refactor earlier this week. Will update you as it becomes more complete.

**Comment by bovine3dom** [comment]
Counts now work but are appended to commands. `repeat [n times] [ex string]` does what this issue wants - but it's a bit broken, see #1538.
