### ISSUE TITLE
Add `hint -c` style default to hints per site configurable by user

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#270]
For example, on $SEARCH_ENGINE, I almost never want to click on my profile or even on the image tabs - I just want to click on the results.

This could probably be solved amicably with per-site bindings.

**Comment by cmcaine** [comment]
Need dem autocmds. This is a good idea, though.

**Comment by glacambre** [comment]
Another option could be to duplicate all settings on a per-domain basis. A user could then do something like `domain example.org bind f hint -c selector`. When looking up settings/key bindings, Tridactyl would first check the settings for the domain and if it can find anything in those, try the global settings.

Matching domains with regexes rather than strings would also let users share settings across multiple domains, which would be particularly useful for services that can be accessed through multiple domains (e.g. youtube.com and youtu.be).

I don't know how reasonable that idea is though. I suppose it could end up being fairly slow/memory-hungry depending on how it is implemented.

**Comment by cmcaine** [comment]
There would be negligible performance impact for any sane implementation.

**Comment by oxysoft** [comment]
+1, this is essential for certain sites like Reddit which have an absurd amount of elements that I will never click. e.g. when browser a subreddit or the front page, I will never hit anything other than links or comments, and maybe a few other things like search etc. I should be able to configure what I want to include as hints.

**Comment by glacambre** [comment]
This should be pretty easy to implement now that we have per-pattern configs.

**Comment by glacambre** [comment]
We now have `bindurl`, which enables exactly this. See the example [tridactylrc](https://github.com/tridactyl/tridactyl/blob/27e8ca37018defff93c63944146b8fbe7cc71412/.tridactylrc#L36) and `:help bindurl` for more information about how to use it.
