### ISSUE TITLE
Default `bind d tabclose` resurrects itself over my `bind d scrollpage 0.5`

### ISSUE THREAD

**Issue by maricn** [tridactyl/tridactyl#2839]
Tridactyl version: 1.20.1pre4591-6d0810f2
Firefox version: Mozilla Firefox 81.0
Operating system: linux

*   Brief description of the problem:

Sometimes while using tridactyl, pressing key `d` closes a tab i was working on instead of scrolling down, per my updated bindings. It happens only sometimes, and so far I've only seen it:
1. after closing other tab, if I press `d` very quickly when the focus is being moved to another tab
2. after opening a new tab, but in that short time before the focus is moved to it, pressing `d`
3. when a tab is generally loading, pressing `d`

Maybe important info is that I'm also running TST, Stylish and Violentmonkey which slow down responsiveness of my 50+ tabs multi-window firefox, especially on github which I experience in a customized way. That leaves some room for this bug to manifest, as the page is loading slower.

*   Steps to reproduce:

1. have `bind d scrollpage 0.5` in your `tridactylrc`
2. open two tabs
3. on one tab navigate to another link
4. QUICK! press `d` repeatedly! pressss ittt!
5. if the tab is still alive, navigate back `<C-[>` per my config, and quickly press `d`
6. keep on navigating back and forward that one tab and very quickly press `d` while it's loading...
7. voila! the old binding that was not supposed to be used has been applied

*   URL of the website the bug happens on:
https://github.com/tridactyl/tridactyl/issues or anywhere really.. haven't tested with some special pages, but tridactyl doesn't work on special pages anyways i guess..

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/maricn/a86720274072a9899d747524e8aacd84/71904ac60cd3e1577ba09eb7d06facea8397ecb9 (rev. 4)

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
sanitise tridactyllocal tridactylsync

" General Settings
set configversion 1.9
set update.lastchecktime 1593077346454
set smoothscroll true
set modeindicatorshowkeys true
set modeindicator false

" Theme
" set theme maricn-base16-gruvbox-dark-hard
" set colours maricn-base16-gruvbox-dark-hard
colourscheme maricn-base16-gruvbox-dark-hard

" Binds
unbind <F1>
unbind <C-f>
unbind <C-a>
unbind <C-d>
unbind <C-u>
unbind .
unbind p
unbind s
unbind S
unbind D
unbind U

bind d scrollpage 0.5
bind u scrollpage -0.5

" conflicts with <C-d> as "Bookmark this page"
" bind <C-d> scrollpage 0.7
" bind <C-u> scrollpage -0.7

bind <C-[> back
bind <C-]> forward

bind i mode ignore
bind --mode=ignore <escape> mode normal

bind t tabnew
bind J tabnext
bind K tabprev
bind x tabclose
bind --mode=ignore ^ tab #

bind / fillcmdline find
bind n findnext
bind N findnext -1
bind <Escape> composite mode normal ; hidecmdline ; nohlsearch

bind --mode=ex <ArrowRight> ex.insert_completion

" For syntax highlighting see https://github.com/tridactyl/vim-tridactyl
" vim: set filetype=tridactyl
```

**Comment by bovine3dom** [comment]
1. It's unwise to have `sanitise` in your RC file as it has been causing bugs that we haven't been able to fix - mostly #1409 - I'd suggest just running it interactively whenever you feel the need to

2. This bug happens because it takes a while for your config to be populated in each page. To fix it we'd need to replace this https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/lib/keyseq.ts#L421 with `await config.getAsync(`, but that would mean rewriting lots of functions above that to be async, which could be tricky. It might also reduce Tridactyl's responsiveness, but I'm not sure. We could instead choose to have a different bug where if the config hasn't been populated we throw an error or just fail silently, but I'm not sure that's better since most people don't change many binds. Normally I'd say we can allow the user to choose with a setting but we obviously can't in this instance : )

Presumably you'd prefer the "fail silently" option since it will just look like Tridactyl hasn't loaded?

**Comment by maricn** [comment]
>     1. It's unwise to have `sanitise` in your RC file as it has been causing bugs that we haven't been able to fix - mostly #1409 - I'd suggest just running it interactively whenever you feel the need to

Thanks for mentioning that, I've removed that first line with `sanitise` now.

>     2. This bug happens because it takes a while for your config to be populated in each page. To fix it we'd need to replace this https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/lib/keyseq.ts#L421
>         with `await config.getAsync(`, but that would mean rewriting lots of functions above that to be async, which could be tricky. It might also reduce Tridactyl's responsiveness, but I'm not sure. We could instead choose to have a different bug where if the config hasn't been populated we throw an error or just fail silently, but I'm not sure that's better since most people don't change many binds. Normally I'd say we can allow the user to choose with a setting but we obviously can't in this instance : )
> 
> 
> Presumably you'd prefer the "fail silently" option since it will just look like Tridactyl hasn't loaded?

Yes, my vote would be to fail silently instead of trying to do the default operation. In my case it's pretty destructive operation.

But more than having it my own way, I'd prefer if we find a solution that doesn't rely on such a compromise. Isn't tridactyl loaded with firefox profile and not on each tab? Can we have a singleton config that is loaded once per extension init? That would improve performance of tridactyl and reduce strain on our machines. I don't have an overview of the code, so I'm just shooting in the dark, but hopefully some mechanism like that could be used (expensive operation here is reading from filesystem i presume, so if we could keep the config in memory across tabs, that should do it).

**Comment by bovine3dom** [comment]
Essentially, I don't think we can.

As an approximately correct overview: WebExtensions have two kinds of script. They have one background script that starts with Firefox and has access to all the useful WebExtension APIs, but doesn't have access to pages (where we collect key events). They also have content scripts which have access to pages and can talk to the background script, but don't directly have access to the useful APIs.

We read your RC file once at startup from the background script (and also read config from Firefox storage). Then, as each page loads, it asks the background script what the current config is, I think (it might actually ask Firefox directly but in practice there's not much difference). Whichever it is, the code asks for the config and Firefox says "I'll tell you later" with an async promise. Once we have the config we store it in memory and keep it updated.

The trouble is that the code that intercepts key events and does or doesn't execute Tridactyl code needs to be synchronous in order to stop pages from also doing things because of those key events. So we can't wait for the config to load.

I think the right behaviour is probably to fail silently and pass keys through to the page if the config hasn't loaded yet - it's not just "as if Tridactyl hasn't loaded yet", Tridactyl really hasn't loaded yet. Alternatively we could not execute Tridactyl commands but block all key events from reaching the page, but I suspect that would be even more confusing to users.

**Comment by maricn** [comment]
Ah, so the page has access to the default config instantly, but asks Firefox to get the current (custom) config and that is what takes time...

That's very unfortunate.. :(

Could we queue events on the page until we get the latest config version async response from Firefox? The delay should be under a second, so shouldn't impact UX as much as executing a random command (who knows what default command lies under some user's custom mapping) in that time span.

**Comment by bovine3dom** [comment]
No, we can't queue because as soon as a key event happens we need to decide whether to pass that key event to the page or not. (IIRC). We're not allowed to suspend the key event and then unsuspend it once we know there's no bind for it.

**Comment by bovine3dom** [comment]
Perhaps it is worth mentioning that our fabled "keyboard API" extension to the web extension APIs would fix this as those events would be managed in the background where we would have access to the config all the time (except for maybe half a second at browser start). The downside is that that code is very stale - https://github.com/tridactyl/keyboard-api - and it might be hard to get it merged into Firefox even if we did get it working, given that Mozilla has substantially fewer people working for it now.

**Comment by maricn** [comment]
OK, thanks for your help. I will try moving the important bindings as close as possible to the default keymap.

I got what I need as far as my issue goes. You can close it or keep it to track the issue, whatever suits you the best.
