### ISSUE TITLE
Setting Space to <C-d> doesn't seem to work

### ISSUE THREAD

**Issue by josh-friedlander-kando** [tridactyl/tridactyl#2860]
Tridactyl version: 1.20.2pre4626-14b65660
Firefox version: Mozilla Firefox 81.0
Operating system: mac

I'd like to override FF's native spacebar action (full-screen scroll) to Vim's <C-d> (half screen scroll) in Normal mode.

Action: `:set <Space> <C-d>` (also tried `:set <kVK_Space> <C-d>`)
Expected: half-screen scroll, but still get full-screen scroll.

Is it possible that this key can't be overridden?

**Comment by bovine3dom** [comment]
Hi, that's not something Tridactyl can do exactly. `:set` is for settings rather than keybinds - it might be worth going through `:tutor` to get more of a feel for Tridactyl. If you've already done that please tell us where we can improve it.

I suspect you'll get what you want with `:bind <C-d> scrollpage 1`, similar for -u but with -1 instead.

**Comment by bovine3dom** [comment]
Oh, I've done the opposite of what you wanted!

`bind <Space> scrollpage 0.5` is what you want : )

**Comment by josh-friedlander-kando** [comment]
Thanks, that seems to work!

N00b question: my understanding was that `bind` is (by default) for Ex-mode commands, and `set` is for normal (like Vim's `nmap`) - I guess that's incorrect?

**Comment by bovine3dom** [comment]
Yeah, that's incorrect : )

The closest thing we have to `map` is `keymap`, which is only for Tridactyl keys - essentially it's for internationalisation where someone doesn't want to rebind every Tridactyl command manually. `bind --mode=` is for binding in different modes.

`set` works mostly like set in Vim, but for boolean options it is `set blah false` rather than `set noblah`.

`:help [command]` will give you help on any given command : )
