### ISSUE TITLE
Tridactyl and waterfox

### ISSUE THREAD

**Issue by Cyberdr3am** [tridactyl/tridactyl#2882]
Hello,
I would like to use tridactyl in waterfox but the extension is not compatible with this version of firefox.
Can you tell me the version I need to take to allow me to use it with this browser.
Thank you

Distro : Manjaro
Browser Waterfox-classic from AUR

**Comment by bovine3dom** [comment]
"Waterfox current" might just work. Otherwise you can build Tridactyl yourself - turn off the version checking by changing 68 to 0 here: https://github.com/tridactyl/tridactyl/blob/5e8f94ff06bd5f143732f2dabd32b08dabf1e65a/src/manifest.json#L105. The version checking is there for a reason, though - it's the oldest version of Firefox that Tridactyl is tested on. You might find that Tridactyl is very broken once you get it running.

**Comment by Cyberdr3am** [comment]
Thanks a lot for your help.
Tridactyl don't whant to work with waterfox so i give up.
Thx for your help
