### ISSUE TITLE
Mention native in exemplar RC

### ISSUE THREAD

**Issue by mvrozanti** [tridactyl/tridactyl#2907]
Very new to tridactyl, coming from VimFx. I tried putting the following on my `~/.tridactylrc`:

    unbind --mode=ex d
    unbind d

To no avail. What am I doing wrong?

**Comment by bovine3dom** [comment]
The second one is what you want - `unbind d`. (Ex mode, perhaps confusingly, is the mode where you type ex-commands - i.e. the command line).

So probably your problem is that the RC file isn't working. Usually it's just because you haven't installed `:native`, but there can be other things that are less easy to fix.

However, you probably don't need an RC file. Just run `:unbind d` interactively and it will persist.

**Comment by mvrozanti** [comment]
I didn't know one had to `:nativeinstall` :)

It works fine now, thank you!

**Comment by bovine3dom** [comment]
Do you know where you heard about the RC file? Ideally we would mention native there.

**Comment by mvrozanti** [comment]
I honestly can't remember, since I've known Tridactyl for a fairly long time but just now decided to use it and I must say, I'm very impressed with all that it can do. 

But maybe there could be a warning in the example RC file itself that the user should run `:nativeinstall` for it to work. I would think most people are looking for that functionality anyway.

Love this repo!

**Comment by bovine3dom** [comment]
That is an excellent idea : )

**Comment by mvrozanti** [comment]
Whoops it's already there. My mistake.
