### ISSUE TITLE
Image to clipboard hint mode

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3079]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard

Not sure how to get the image to the background script, though.

**Comment by Rummskartoffel** [comment]
I've looked it up and I think we need to do the following:
1. `fetch` the image
1. get the blob
1. check the MIME type, because the API only supports jpeg and png, and throw an error if it's a different one
1. convert it to an `ArrayBuffer` and pass that to the Clipboard API.

We'll need to do the fetching in the background script because of CSP, so we have to pass the image's `src` to a background function.

**Comment by Rummskartoffel** [comment]
I'll take a shot at implementing the background part.

**Comment by bovine3dom** [comment]
Getting the image URL to the background should be easy (with the caveat that you'd need to convert relative addresses to absolute ones, probably worth adding a method for that to lib/dom.ts).

```
:hint -cF img e => tri.excmds.jsb("do whatever you need in background here" + e.src)
```

**Comment by Rummskartoffel** [comment]
Sounds good to me. I actually think it would it'd be good to make this an excmd as well – something like `:yankimage` maybe – to make it easy to write custom image yanking aliases.
