### ISSUE TITLE
sanitise all deletes all logins

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#3109]
Hi,

I just run `sanitise all` in an attempt to clean my settings and start afresh.
After doing that I restarted Firefox.

I was very surprised to find out that all my logins have now been lost.
My `logins.json` file is now empty.
I tried with a test profile and was able  to replicate.

Is this intended behaviour?
If so, I would suggest displaying a very clear warning before using this command.

If it's not intended behaviour, then I don't think it's right that an addon should be able to wipe logins.
I would suggest P1, if you agree.

Thank you

Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 83.0
Operating system: win

**Comment by bovine3dom** [comment]
First off - I'm really sorry that all your logins were deleted unexpectedly. If that happened to me I would have a very stressful few days. I personally keep multiple backups because it's the sort of thing that keeps me awake at night.

However, it is intentional that `sanitise all` deletes them. In our defence, it does give a link to the Mozilla page where the API is described and says that those can be arguments. `:sanitise all` is then listed next to "deletes everything" and must be manually typed by the user. Since the only possible place to find the command is the help page, I think it is safe to say that users running the command will generally have read that help page.

So I think we can just edit the help text to explicitly state that "everything" includes login details, and hopefully no-one else will suffer your fate : )

We should probably change https://github.com/tridactyl/tridactyl/blob/46f59ecdf8233b68e41473d2f6750fe2168d94d6/src/excmds.ts#L3760 to say "Deletes various parts of Firefox or Tridactyl data".

Thanks for filing this issue.

**Comment by Noexpert** [comment]
Thanks for the quick response.
Thankfully this was on "test" profile that I keep, so no real damage done!
