### ISSUE TITLE
;x ;X hint mode click in incorrect places

### ISSUE THREAD

**Issue by osleg** [tridactyl/tridactyl#3214]
Tridactyl version: 1.20.4pre5061-6f00a7dc
Firefox version: Mozilla Firefox 84.0.1
Operating system: linux

### Brief description of the problem:
When using ;x or ;X commands xdotool clicking in incorrect place.

### Steps to reproduce:
There are 2 issues to this problem:
1. HighDPI screen scaling:
  invoking ;x hint mode and selecting hint at the middle of the screen brings
  mouse cursor roughly to the middle height of the screen and 1/4 of the width.
  Roughly because my scaling factor is 1.75.
  It seems that there's no accounting of scaling when calculating x and y
  positions.
3. xdotool invocation options:
  It looks like currently Trydactyl is trying to run xdotool without --window
    argument and thus acting on entire screen.
	Instead it might be better to act on Firefox window only. 
  For firefox it's a bit tricky because you need to select by the ID of the tab
  being visible right now. To achieve this following script can be used assuming 
  the tab name is known and passed as first argument pos x and y as 2 and 3 args:
```
#!/bin/sh
pids=$(xdotool search --class "firefox")
for pid in $pids; do
    name=$(xdotool getwindowname $pid)
    if [[ $name == *"$1"* ]]; then
        exec xdotool mousemove --window $pid $2 $3
    fi
done
```

edit: wording

**Comment by magnus-ISU** [comment]
Is the second issue really a problem? I suppose if you have a popup appear in the short time between executing ;x and actually getting the click event, or if you are trying to click on something behind another window for some reason, but at least for me it has worked great so far, and the fix you propose complicates the behaviour a lot for a few niche cases, and I think would be better suited for a wiki article detailing some "extra things" you can do or something. After all

hint -F e => { const pos = tri.dom.getAbsoluteCentre(e); tri.excmds.exclaim_quiet("xdotool mousemove --sync " + pos.x + " " + pos.y + "; xdotool click 1")}

is easier for me to understand and extend than

hint -F e => { const pos = tri.dom.getAbsoluteCentre(e); tri.excmds.exclaim_quiet("for pid in $(xdotool search --class "firefox"); do if [[ $(xdotool getwindowname $pid) == *"$1"*]]; then exec xdotool mousemove --window $pid $2 $3; fi; done )}

I also want to note that firefox forks can also run tridactyl. Of course as long as its an easy workaround like redoing your :bind ;x then there is no problem, but if tridactyl could extract the actual class of the window (for me "waterfox" for example) that would be better than hardcoding it to firefox. (not sure if such a thing is possible though).

**Comment by bovine3dom** [comment]
I'm pleasantly surprised that anyone found and used this bind - could you both say what you're using it for? It was really supposed to be an absolute last resort when nothing else worked.

Regarding Waterfox - we already have a setting where you can change the name of the Firefox binary, https://github.com/tridactyl/tridactyl/blob/1522f0900cabfd8d95dfa223231772fee61938b7/src/lib/config.ts#L907
and also `ff_cmdline` to work it out automatically (in fact we should probably move everything over to trying `ff_cmdline` first). But surely we can just use the active window?

HiDPI shouldn't be too hard to handle, I think we can read that quite easily (pixelsPerPx?).

**Comment by magnus-ISU** [comment]
There are certain times on a website that f won't work, or won't work how I expect it to (because I basically expect f to click on an element generally). Often, ;x will fix that. For example, logging in to reddit there are four different elements that I can type in and using f not a single one works. Using ;x, of course, and actually clicking it does work.

Also sometimes there are a ton of congested hints in a small area, most of which do nothing (like the youtube comment section for example). ;x doesn't actually fix that usually, but at least since it visually moves the mouse I can see where that element is.

I actually only the bind yesterday, but I'm very glad I did already. In fact I rebound another key (c) to the same thing (just added a second xdotool call to move the mouse back off the screen, which is nice since I can get it out of the way easily now) since I didn't have c bound and it makes sense to me (click) and I'm starting to use c interchangeably with f lol.

**Comment by glacambre** [comment]
>HiDPI shouldn't be too hard to handle, I think we can read that quite easily (pixelsPerPx?).

window.devicePixelRatio :)

**Comment by bovine3dom** [comment]
@osleg could you explain why you think we should use the `--window` option? It works fine for me without it, no matter where I put the window on the screen.
