### ISSUE TITLE
Allow <C-c> to copy (and perhaps <C-a> to select all) in the command line, or modify tutorial

### ISSUE THREAD

**Issue by Jerror** [tridactyl/tridactyl#3229]
This issue was raised by Lexi in gitter.
I can't reproduce the problem exactly since I've already unbound the culprits, and `reset` yields a different binding than described; perhaps because I use beta? Anyway, it's a case of different-binding-same-problem. I'll discuss the behaviour as reported by Lexi.

By default `<C-c>` in ex-mode is (purportedly) bound to exit to normal mode, which has the effect of making text impossible to copy from the command line. The solution as suggested by bovine3dom is to `:unbind --mode=ex <C-c>`. This is part of bovine3dom's example tridactylrc (as good a benchmark for default settings as any) along with `:unbind --mode=ex <C-a>` to allow select-all in the command line. Perhaps these bindings should be changed or released to allow `<C-c>` and `<C-a>` to function as most users might expect.

If not then the command line tutorial should be amended. At the top of the listed keybindings is
"Ctrl-C to exit to normal mode, or copy selected text."
This is false; only the former works. This suggests to me that the present behaviour is a bug. As far as I can tell, having these chords bound by tridactyl at all overrides the standard copy / select-all behaviour so it is not possible to have them pull double duty.

I would recommend changing the default "exit to normal mode" binding to `<C-g>`, which is the standard "cancel any command or prompt" binding in emacs and its vim-centric derivatives. Since tridactyl uses 'g' as a prefix to commands, `<C-g>` seems natural as a binding to cancel commands.

I would discuss a new binding for whatever `<C-a>` by default does but in beta 1.20.4pre5084-70d56c2a when I reset `<C-c>` and `<C-a>` I get "text.kill_whole_line" and "text.beginning_of_line" respectively. The former doesn't match the reported default behaviour (in the tutorial, and by Lexi) so I don't trust what `reset` tells me for either.

**Comment by bovine3dom** [comment]
Ctrl-c should cancel and close the command line, as it does in Vim. It's possible that we messed up somewhere when we made ex-mode binds configurable.

https://github.com/tridactyl/tridactyl/blob/1522f0900cabfd8d95dfa223231772fee61938b7/src/lib/config.ts#L127 - this is a surprise to me, I would expect it to behave identically to escape.

@glacambre perhaps you can shed some light on this? Was not closing the command line intentional?

I've personally wanted it to be bound to "copy selected text or empty and close command line if nothing is selected" for ages but I've never got round to doing that. I suppose that's what the tutorial is suggesting but I'm not sure why it's doing that.

---

I agree that it's surprising to some users but it is how it works in Vim and Vimperator. I think it could be more surprising to our current users if we unbound it now after ~3 years...

**Comment by Jerror** [comment]
> I think it could be more surprising to our current users if we unbound it now after ~3 years...

I agree with this. I'd planned to address just the deviation from the behaviour described in the tutorial, but when I found that <C-c> apparently changed default in beta I figured stability and vim-fidelity were not priorities here. I'm content to be wrong!

**Comment by glacambre** [comment]
>@glacambre perhaps you can shed some light on this? Was not closing the command line intentional?

This code is [two years old](https://github.com/tridactyl/tridactyl/commit/00c01ec6ec6c936f2f516986f838858e1e55a6b4), that's too much to ask from my poor old brain ;). I don't think this was intentional (But maybe it was? `<C-c>` in a shell doesn't kill the shell, it just shows you a new prompt. That's a departure from what Vim does though...) and since nobody complained about this backward-incompatible change I think we can safely say that nobody uses `<C-c>` and remove the binding.

**Comment by bovine3dom** [comment]
Yeah, sure, let's bin that bind. Do many people use ctrl-a?
