### ISSUE TITLE
"search" Not respecting browser Search engines

### ISSUE THREAD

**Issue by schmitmd** [tridactyl/tridactyl#333]
If I use "tabopen search" or "open search", it sends me straight to Google despite me having removed all search engines but DuckDuckGo in my browser settings.

If I type things into the address bar, tridactyl correctly uses DuckDuckGo.

If I can help diagnose/fix this somehow (without knowing anything in TypeScript or JavaScript), please let me know.  Thanks!

**Comment by glacambre** [comment]
We're already aware of this issue, unfortunately we can't do much about it for now: Mozilla doesn't give extensions access to the user's search engine preferences. If you wish to use DuckDuckGo instead of Google, you can use this command: `:set searchengine duckduckgo`. You can also create your own custom search engines using `:searchsetkeyword myengine https://myengine.com/?q=`.

This issue is frequently mentioned by users, even though we talk about it in the [FAQ](https://github.com/cmcaine/tridactyl#frequently-asked-questions). In your opinion, what should be done in order to make finding information about this issue easier for new users?

**Comment by schmitmd** [comment]
I'm very sorry!  I must have either missed that in the FAQ or thought it was redundant (figured browser settings would be available to the extension).  I definitely searched through the issues, but left on github's default "is:open" criteria, assuming that if it was still a problem, it would be an open, active issue.  I now see #240 is the same thing.

I think, actually, leaving this (or a similar, with buzzwords like "Google," "default," etc.) issue open and flagging it Blocked pending whatever API additions (<insert link>) are needed would be helpful.  This  might be a good way of catching people with useful info before they go creating duplicates of duplicates.  That way, people know that it's an outstanding issue with a workaround (and they can subscribe for updates on progress).

**Comment by bovine3dom** [comment]
#73 has been left open for that very reason.

Don't get your hopes up for this being fixed - Mozilla want to kill keywords eventually.

**Comment by cmcaine** [comment]
Keyword seaches != browser search engines. Might as well leave this open.

**Comment by bovine3dom** [comment]
Heh. One of the reasons Mozilla want to kill keywords is because they are confusing when they also have browser search engines. Confusion I just fell victim to. :(

**Comment by HeidiSalami** [comment]
> In your opinion, what should be done in order to make finding information about this issue easier for new users?

I read that part of the FAQ but though that was an option to add new engines. I did not get, that firefox search engine settings weren't used from that text.

**Comment by glacambre** [comment]
Search now respects browser search engines in the betas. See `:h searchengine` for more information :)

**Comment by schmitmd** [comment]
Awesome.  Thank you so much!
