### ISSUE TITLE
nativeinstall or nativeupdate fails on 32 bit armv7h Linux (chromebooks, raspberry pi 2 etc) : wrong binary type

### ISSUE THREAD

**Issue by m040601** [tridactyl/tridactyl#3410]
I've only noticed today, that the native in Tridactyl switched from the Python version to a compiled version in January 2021. T

Tridactyl version: 1.21.0
Firefox version: Mozilla Firefox 86.0
Operating system: linux

This is what an arm (32bit) Samsung Chromebook will say:

uname -a
`Linux alarmsung 5.10.16-1-ARCH #1 SMP PREEMPT Sat Feb 13 19:42:53 UTC 2021 armv7l GNU/Linux`

echo $OSTYPE
`linux-gnueabihf`

And this is what an arm (32bit) Raspberry Pi 2 will say:

uname -a
`Linux alarmpi 5.10.17-2-ARCH #1 SMP Tue Feb 23 22:42:38 UTC 2021 armv7l GNU/Linux`

echo $OSTYPE
`linux-gnueabihf`

The process of installing the native tridactyl involves downloading and running  a script:

`  $ curl -fsSl https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/install.sh -o /tmp/trinativeinstall.sh `

That will further pull the compiled binaries from github. These are pulled from

`https://github.com/tridactyl/native_messenger/releases/download/$native_version/native_main-$binary_suffix`

**$binary_suffix`** gets its value from $OSTYPE

and as you can see it's the wrong, ELF64 binary, for this, arm 32, architecture, 

file ~/.local/share/tridactyl/native_main 

`/home/mmc1/.local/share/tridactyl/native_main: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=0404cf594c7d3cb28c047c68099d9d3b04a07fea, not stripped`

If I check, https://github.com/tridactyl/native_messenger/releases/tag/0.2.5 , I see that only 3 types of binaries are being produced:

> 
> native_main-Linux
> native_main-macOS
> native_main-Windows

That is, no binary for arm (neither arm32 nor arm64)

Am I corrrect ? This is sad, because the **python "native_main.py"** Tridactyl had been working fine for more than a year, and now the change to a precompiled binary has suddendly made it stopped working.

The same thing applies to every other arm Chromebook or Raspberry PI. Whether 32bit or 64bit..

A pity because it's preciselly these low powered devices that benefit the most from an aggressive Firefox customization to block tracking/adds and make them more keyboard friendly.

----

UPDATE1:

Just saw, https://github.com/tridactyl/native_messenger/issues/12

> ....I'm not sure this is actually worth doing, though, as no-one uses 32-bit machines these days, right?...Also arm64 for Pinebooks etc.
> @bovine3dom bovine3do

**Comment by bovine3dom** [comment]
Thanks for reporting this. I honestly forgot that I had meant to make an arm build.

In the meantime you can install the old python messenger using this script: https://github.com/tridactyl/tridactyl/blob/master/native/install.sh

**Comment by m040601** [comment]
Good to know many architectures will continue to be supported.
So many different options nowadays to automate this builds for free with Github Actions. etc.

> ....I honestly forgot that I had meant to make an arm build.

No problem at all. And again, thanks for all this **amazing** and **underrated** work you've been doing . It's the only reason I still even care to  use Firefox. It's mind boggling how a couple of guys fightting an ever growinng monstruosity of Javascript complexity and standards, can make a more usefull tool than a million dollar corporation like Mozilla.


If I might suggest though, here is some tips for better communicating the project through the "Changelog" and others.

> I've only noticed today, that the native in Tridactyl switched from the Python version to a compiled version in January 2021.

I have now noticed that indeed, acording to , https://github.com/tridactyl/tridactyl/blob/master/CHANGELOG.md :

> The native messenger is now written in Nim and is much faster (especially noticeable on :editor).

**Comment by bovine3dom** [comment]
> So many different options nowadays to automate this builds for free with Github Actions. etc.

We already do this : ) https://github.com/tridactyl/native_messenger/blob/master/.github/workflows/release.yml

> And again, thanks for all this **amazing** and **underrated** work you've been doing . It's the only reason I still even care to use Firefox. It's mind boggling how a couple of guys fightting an ever growinng monstruosity of Javascript complexity and standards, can make a more usefull tool than a million dollar corporation like Mozilla.

Thanks, but Firefox takes care of most of the worrying about JavaScript for us. As for being more useful, I think most of the population would disagree with you :P

> Still dont' know how I missed that [changelog]. I mean it's in front of me every time I open a new tab.

Yeah, it's a delicate balance between being obvious enough to spot (it even gets a little red label when there's new stuff on it) and subtle enough so that it's not too annoying.

I personally _hate it_ when an extension opens a new page when it updates just to tell me what has changed - 99% of the time I don't care.

If you have any ideas I'm all ears!

> > The native messenger is now written in Nim **and is much faster** (especially noticeable on :editor).
> 
> Ahhh .. that's important.

I do try to put the most important stuff at the top of the changelog, but IMO a performance enhancement isn't very important - all users will benefit from it without needing to know about it. It's the new features that need highlighting because otherwise people won't find them. Do you strongly disagree?

> And, indeed, I had noticed in the last days that in my deskop x64, Tridacty felt much snapier.

For what it's worth, this is probably a placebo. Speeding up the native messenger should only have sped up a few things, like using edit-in-vim, open-in-mpv, file-system completions, etc. Most of Tridactyl should be unaffected.

> But ut kind of goes unnoticed, and is tucked away in a very very long list under "Miscellaneous". That changelog is big, very big. The changelog messages are, and I hope continue to be, very detailed and include "New Features", "Bug Fixes" "Miscellaneous".
> 
> This is all good. But it includes complex techical changes for developers, mixed with practical info for non techical users.
> 
> Why not make a section "Highlights" or "Cant miss in the Edition" at the top ?
> Just the big "PR" and "newspaper" worthy average Firefox Joe user thing.

This is a good idea, I'll try to remember to do it next time. Thanks!

I do write a human-readable newsletter each quarter that gets emailed out to donors. You can see them on our website when I remember to put them there - http://tridactyl.xyz/newsletters/. That page provides an RSS feed (`:rssexec` is great if you didn't know about it : )) http://tridactyl.xyz/newsletters/index.xml too.

> Give also the "Thanks" section more prominence.

It'd be nice to do this but I don't want to further hide the useful parts of the changelog, as you said they're already quite long...

> And emphasize and repeat the call for donations.

It feels a bit strange to do this on the changelog which, I assume, most people read via the new tab page which already asks for donations quite (perhaps too) loudly. Donations have gone down quite a bit over the last few months though so perhaps I should try it.

**Comment by m040601** [comment]
> .... It's the new features that need highlighting because otherwise people won't find them. Do you strongly disagree?...

No I dont' disagree at all.

Actually another example of these "new features that need highlighting" and how I also missed some is this one.

The, how should I call it, the "completion mechanisms" usability. How snapy and confortable it is and how easy it is to get help when you start typing and/or use the TAB and Space keyes. How do the few words of "description" of the commands fill in as you type. How does i

I am now completely "spoiled" by Qutebrowser's superb interface.
Since the early days of Tridactyl, I could not find the same snapiness of course.

But I refrained from opening any issues, because I knew it was gonna be a matter of time before things got improved. And indeed,


Geesh, I really have to find the time to write an in depth review of my Tridactyl usage. I'm a power user and have been folllowing you since the Pentadactyl days.

**Comment by bovine3dom** [comment]
Those are some great uses of the hint mode!

You could add some pages to the wiki, if you like - it is quite barebones at the moment: https://github.com/tridactyl/tridactyl/wiki

**Comment by bovine3dom** [comment]
@m040601 could you try the `native_main-Linux` executable from here? https://github.com/tridactyl/native_messenger/actions/runs/606200428#artifacts (this link will die in ~30 days). You'll need to put it where the previous binary was (with the same name as the previous binary).

You might need to run `:nativeinstall` again first to tell Firefox where to find the binary.

**Comment by m040601** [comment]
Just did that.
Download and unzip.

`  $ file native_main`

> 
native_main: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-a

# Native messenger is correctly installed, version 0.3.0

**Comment by bovine3dom** [comment]
`armhf` builds added in https://github.com/tridactyl/native_messenger/pull/39

It'll be a while before `:nativeinstall` actually works as we'll need to make both a native (that repo) and a webextension (this repo) release.
