### ISSUE TITLE
ci/lint.sh might be a placebo

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3477]
`yarn run eslint --ext .ts` doesn't seem to ever throw any errors, whereas `yarn run eslint src/*.ts` does.

I've noticed that "prettification" errors seem to sneak their way into the code base quite often which, in theory, the CI should prevent.

**Comment by Rummskartoffel** [comment]
Not sure that's the cause of this, but I think there's something wrong with the ESLint config we use. Every time I've opened the RC VS Code has screamed at me. I've never really bothered trying to fix it, though, because it has always worked for my purposes.

**Comment by lydell** [comment]
`yarn run eslint --ext .ts` – this does not specify any files or dirs. ESLint oddly does nothing then. I think you mean `yarn run eslint --ext .ts .` (note the `.` at the end). (Use a .eslintignore if that lints too many files. Note that you can use [overrides](https://eslint.org/docs/user-guide/configuring/configuration-files#specifying-target-files-to-lint) instead of `--ext` if you want to be able to do just `yarn run eslint .` which is always nice.)

**Comment by bovine3dom** [comment]
Thanks @lydell, that seems to have fixed it!
