### ISSUE TITLE
bind an ex command to a specific search engine

### ISSUE THREAD

**Issue by honestSalami** [tridactyl/tridactyl#3501]
Tridactyl version: 1.21.1
Firefox version: Mozilla Firefox 86.0.1
Operating system: linux

-   Brief description of the problem:

I'm trying to bind an ex command to a specific search engine on a webpage, following the recommendation in this [issue](https://github.com/tridactyl/tridactyl/issues/194#issuecomment-348707159). But when I try to run the ex command, it does not exist. It does not seem to appear in the bound commands list.

-   Steps to reproduce:

    1. write ```bind --mode={ex} ety fillcmdline_notrail open https://www.etymonline.com/search?q=```
    2.   try to execute ```:ety``` ex command
    3. fail with Error: not an excmd: ety

-   Config:
https://gist.github.com/honestSalami/e9d03e69f10e5caaae47a45d52d9f133

**Comment by bovine3dom** [comment]
There's quite a few misunderstandings here:

1. that issue is so old that it was before we had user configuration (!) - you probably want to do `:set searchurls.ety https://www.etymonline.com/search?q=` and then you can do e.g. `:open ety codswallop`, `:tabopen ety codswallop` etc.
2. `bind` binds sequences of keys to ex-commands, so if your invokation had worked you would have to press `e t y` and then the command line would appear
3. `bind --mode=ex` is the correct syntax for binding keys in ex-mode (i.e. no `{}`), _but you don't want to do that_, that means that you're making keybindings for the command line. Like how `<Tab>` selects the next completion, except you would bind to `e t y` ... so you would never be able to type the letter e in the command line : )
4. if you wanted to make a new ex-command you would use `:command`, e.g. `:command ety fillcmdline_notrail open https://www.etymonline.com/search?q=`, then `:ety` would run the command

I'll edit that comment you linked to. If you know of any other confusing documentation we can improve please tell us. Sorry that we misled you!

**Comment by honestSalami** [comment]
oh, don't worry! thanks to you for solving my problem so thoroughly. I'm just glad to leave a breadcrum trail for others to follow. If I find anything else while I use tridactyl, I'll make sure to post it.

thanks again!
