### ISSUE TITLE
Please provide an option to not take over the new tab page

### ISSUE THREAD

**Issue by usernamenumber** [tridactyl/tridactyl#384]
By default when you open a new tab, it loads the tridactyl help page. Please provide an option to disable this behavior.

Specifically, this is a problem because it breaks Tree Style Tabs' "open new tab as a child of the current tab" feature, because TST identifies new tabs by url e.g. `about:newtab`. That url is configurable, but because the tridactyl page doesn't have (or at least doesn't show) a url, there's nothing for TST to match so it never identifies new tabs. 

As a workaround in the mean-time, if there is a url string that will allow TST to match tabs opened to the Tridactyl help page, I'd be happy to know it. 

Thanks for making tridactyl!

**Comment by usernamenumber** [comment]
Ah, looks like the [option does exist](https://github.com/cmcaine/tridactyl/blob/master/src/static/newtab.md#how-can-i-get-rid-of-it) as a `:set` command. 

It would still be handy to have a string I could give TST while still keeping the tridactyl newtab page, though, and as this is more about plugin behavior that vi behavior it would also be nice to have it as an option on a plugin preferences page. 

If neither of those are likely to happen though I've got enough to work with so feel free to close this issue if that's the case.

**Comment by glacambre** [comment]
In order to get Tridactyl's newtab url page you can do this:
1) Go to the newtab page
2) Open the dev tools (you can do this with `Ctrl+Shift+I`)
3) In the console, type `document.location` and press enter
Unfortunately this isn't a great option because this URL changes between versions and maybe even between installations. Also, I'm not sure other extensions have access to it :/

**Comment by bovine3dom** [comment]
We could potentially use the permissions API https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/request to ask for permission to set your new tab page after install, and you could deny us that... but the magic permission for new tabs is not currently part of that API.

Other extensions don't have access to our new tab page, but we can get the URL programmatically and could expose an API if people wanted it, but it seems like it would have a very limited use case.

Issue #377 sounds like your best bet. I'd be happy to help if you wanted to have a go at implementing that.

**Comment by usernamenumber** [comment]
Thanks for the quick responses! 

Just for the record, I can confirm that telling TST to match the help page's url (`moz-extension://$UUID/static/newtab.html`) did not work.

#377 is interesting! I'm unclear how it would help in this situation, though. Do you mean have tridactyle set up some kind of hook in TST's API that will let it communicate the newtab url to TST, or take over handling new tab behavior for it? Something else?

I haven't done any plugin authoring before and have precious little time to spend, but if I can get an evening or two to poke around I'll let you know if I have questions. Thanks for the offer.

**Comment by bovine3dom** [comment]
I think the easiest way would be to reimplement TST's "open as child" within Tridactyl as a setting. You'd need to add a bit to `tabopen` using TST's API to check what the current tab was, and attach the new tab as a child.

I don't think we would be able to fix tabs opened with Ctrl-T or the GUI, though.

**Comment by glacambre** [comment]
Another solution could be to have TST send a request to tridactyl when a new tab needs to be opened. This would require adding code to TST though and it might not be interesting for TST's maintainer to do it since the amount of users that use both TST and Tridactyl must be pretty low.

**Comment by cmcaine** [comment]
> I don't think we would be able to fix tabs opened with Ctrl-T or the GUI, though.

If we can do it for :tabopen, we can do it for the others.

Re: Disabling new tab page completely

We could provide the new tab page as a companion extension and prompt users to install it or not. It'll be a bit tricky to do it, but it's possible.

**Comment by hvdijk** [comment]
It's a problem even without TST.

`set newtab about:newtab` to restore the default new tab page doesn't work at all, even though explicitly navigating to `about:newtab` does go to the default new tab page. (I understand and accept that Tridactyl won't work on that page.)

`set newtab about:blank` sort of works, but not entirely. It does go to `about:blank`, but Tridactyl's page pops up briefly beforehand, a history entry gets added, Tridactyl's favicon remains on the tab, and there's something messing with the keyboard focus somehow that I haven't entirely figured out yet.

> We could provide the new tab page as a companion extension and prompt users to install it or not.

Yes please, at least while waiting for Mozilla to allow for some simpler option.

Workaround for me: for now it's possible to install the New Tab Override extension, which seems to somehow override Tridactyl rather than conflicting with it. But I don't know if that will solve the problem with TST.

**Comment by jasontibbitts** [comment]
For me, `set newtab about:newtab` does appear to work (Firefox nightly on Linux), with the caveat that the Tridactyl help page does appear briefly.

I can understand this if I'm opening the new tab page via some binding I set inside of Tridactyl, but if I'm using Ctrl-t as usual, it would be nice to just let Firefox do what it normally does without Tridactyl getting involved.  I tried to unbind C-t (just in case) but somehow now I get two new tabs, one with the Tridactyl help page and one with the usual Firefox new tab page.  Not sure how I managed to mess that one up.

**Comment by glacambre** [comment]
>it would be nice to just let Firefox do what it normally does without Tridactyl getting involved

We'd love to but we can't. Tridactyl must [specify](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/chrome_url_overrides) what page should be used in order to override the newtab page in a [specific file](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json) that is always loaded and that doesn't let developers ask users if they really want to override the newtab page or not.
The reason you're seeing Tridactyl's newtab page flash for a second before you get the page you set in your `newtab` setting is that we had to implement a hack that makes Tridactyl's newtab page redirect you to whatever you set as `newtab` setting.
I believe this is the best we can do without splitting Tridactyl into two extensions.

**Comment by bovine3dom** [comment]
The new tab override extension apparently looks less janky, so we should look to see how it works at some point.

**Comment by c02y** [comment]
Hello, I need help, by default without using tridactyl, the new tab page of Firefox opened by Ctrl-t contains a search box and "Top sites", etc, how can I use this default page as the new tab page opened by Ctrl-t while still enabling tridactyl?

`set newtab about:blank` or `set newtab about:newtab` will make the new tab page opened by Ctrl-t empty which is useless to me.

**Comment by bovine3dom** [comment]
Please see issue #534 - I'd be happy to provide space to host such a build. It's probably only a few lines you need to change.

**Comment by ELLIOTTCABLE** [comment]
Of note here when considering alternatives — every time Tridactyl updates itself, I've been `yy`'ing the newest `newtab.html` URL, and pasting that into my FireFox preferences to ensure that new *windows* will *also* allow me to use Tridactyl commands:

![image](https://user-images.githubusercontent.com/200/49960430-c4520980-fed5-11e8-81be-afbdfbc7e4d8.png)

I can't imagine I'm the only Tridactyl user that'd like to see the new-tab and new-window behaviour synchronized; so providing a more-permanent newtab URL or something of that sort may be more useful than just for this single TST feature!

**Comment by glacambre** [comment]
> so providing a more-permanent newtab URL or something of that sort may be more useful than just for this single TST feature!

Unfortunately we can't choose the newtab page's "domain name", it's automatically generated by Firefox. We could make Tridactyl write its newtab page url to user/pref.js every time it closes though, but it'd require two restarts after an update to take effect.

**Comment by bovine3dom** [comment]
We could probably steal a URL via browser request interception, e.g. home.tridac.tyl?

**Comment by samrocketman** [comment]
I don't like it at all in general.  It should only open after the plugin is first installed and never again (for release notes).  For all other uses, `:help` is good enough.

**Comment by wavexx** [comment]
Likewise, I manually modify the page to be completely blank.

**Comment by bovine3dom** [comment]
I'm still happy to build, distribute and sign a version without the new tab page so long as someone makes a PR that edits scripts/sign to make one. I think you literally just need to delete a key from manifest.json.

**Comment by samrocketman** [comment]
I'm not sure what's involved with writing it but just giving my opinion.  If it doesn't align with the direction you want then no worries.  I'm just happy to have something like vimperator again.

**Comment by bovine3dom** [comment]
Separate build now available at https://tridactyl.cmcaine.co.uk/betas/nonewtab/ without new tab page - has quite a few issues, see https://github.com/tridactyl/tridactyl/labels/nonewtab.

Thanks @mphe and @cmcaine.
