### ISSUE TITLE
Switch tridactyl theme depending on the system theme

### ISSUE THREAD

**Issue by azmeuk** [tridactyl/tridactyl#3882]
Some OS have dark and light variants of their themes. For instance GNOME have [an extension](https://extensions.gnome.org/extension/2236/night-theme-switcher/) that switches automatically the themes depending on the time or the luminosity.

Other Firefox extensions like [darkreader](https://addons.mozilla.org/fr/firefox/addon/darkreader/) can automatically detects the system theme, and adapt accordingly.

I think this would be awesome if tridactyl could let the users choose a dark theme and a light theme, and use the one or the other depending on the main system theme.

What do you think?

**Comment by bovine3dom** [comment]
I think the easiest way to do this would be to make a new theme, e.g. "auto", and use the newish media directive https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme to change the relevant Tridactyl CSS variables. Since the default theme is always applied you would just need to add a dark mode rule.

**Comment by aaronrancsik** [comment]
I guess this can be closed :)

**Comment by bovine3dom** [comment]
If you had said "fixes #3882" in your PR it would have been closed automatically when the PR was merged :)

**Comment by aaronrancsik** [comment]
Ops, next time I will keep in mind.
