### ISSUE TITLE
Visual mode doesn't accept [count]<char> , also can't bind v_<number><char> as temp solution

### ISSUE THREAD

**Issue by m2habert** [tridactyl/tridactyl#3901]
In visual mode, whenever [count] is used in order to vim-like fast select, as in  :
    
    <5w> or <8j> or <4k>

tridactyl does not accept it, returning the error message:

`controller in excmd: SyntaxError: unexpected token: numeric literal`

Ok, no problem, visual mode is still in beta, it cannot all be roses. But if I try to hack-it-up like:

                      command v_line_up js document.getSelection().modify("extend","backward","line")
                      bind --mode=visual k v_line_up
                      bind --mode=visual 4k composite v_line_up ; v_line_up ; v_line_up ; v_line_up
 or better yet:

                      bind --mode=visual 4k repeat 4 v_line_up

and then press <4k>,  tridactyl still refuses to play along, and the same "unexpected ... numeric literal" message is given.

 ¿Any way I could get what I want? ¿Why can't I map number-letter combinations?

 (¿should this be referenced in #3408 ?)

Thanks!

**Comment by bovine3dom** [comment]
Tridactyl handles counts very simply: given that `[key sequence]` is bound to `[ex command]`, `N[key sequence]` where `N` is a number is bound to `[ex command] N`. So "all" you need to do is make the commands you want do something with the `N` that gets appended to them, probably with `js -p ... JS_ARG`.

You can't bind to number-letter combinations because, at the moment, that would then stop you using that number in any other count.

Happy to give you more hints if you need them : )
