### ISSUE TITLE
Check whether new beta gets any users

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4247]
I found beta 1.22.1pre6337 really hard to install - updating didn't work, I had to remove Tridactyl and then re-install it manually _twice_ to get it to work, in addition to fighting with my window manager to get it to show the prompt that said it needed more permissions.

So far the statistics dashboard - private link https://addons.mozilla.org/en-US/firefox/addon/tridactyl2/statistics/usage/versions/?last=30 - says that only three people have managed to get it to install. Usually ~10% of users get the beta by the end of day 2 after release. I need to remember to check again in a few days to see if it stays that low.

![image](https://user-images.githubusercontent.com/6505246/170472332-e95ccbe1-17d8-4a56-87db-ea63c20e7daf.png)

If it doesn't fix itself, I guess we'll have to do a proper release and rely on our own update checker to tell users that something is wrong.

**Comment by bovine3dom** [comment]
![image](https://user-images.githubusercontent.com/6505246/190095875-3cf98f9c-a492-4ac4-8e78-5e095ccd049e.png)

It does seem to be very slowly getting more users, maybe it is less broken than I thought.

**Comment by cmcaine** [comment]
Looks like Mozilla hated 6337 for some reason, but updates from 6237->6426 are going at the expected rate for a release that requests new permissions and 6337->6426 at the expected rate for a release which doesn't need new permissions. So, if we have this situation in the future, we can just try releasing more often to workaround whatever the issue is.

![image](https://user-images.githubusercontent.com/6000761/203578780-43c94df2-0431-4964-ad70-0d177e3c2c3b.png)

**Comment by bovine3dom** [comment]
Thanks Colin, looks like I can close this issue and stop worrying about it :)
