### ISSUE TITLE
Publish the old Tridactyl Tips & Tricks newsletter publicly

### ISSUE THREAD

**Issue by GHolk** [tridactyl/tridactyl#4330]
There is a **Tridactyl Tips & Tricks** newsletter for the donors of tridactyl, and Bovine3dom kindly promised to make the old newsletters public.

> I'll probably make each newsletter public after a couple of months as I don't like restricting knowledge needlessly 
> -- [Tridactyl Tips & Tricks #1](https://github.com/tridactyl/tridactyl/blob/master/doc/newsletters/tips-and-tricks/1-hint-css-selectors.md)

I believe it will be helpfull for people who want to learn tridactyl more and hack it.

Please let me know if there are anything I can help.

**Comment by hendryque** [comment]
Still open, no response?

**Comment by bovine3dom** [comment]
Sorry, no conspiracy here, just incompetence :)

I tried a few months ago to release them but I couldn't get `hugo` to rebuild the website due to some incompatibility between versions.

I think now that the site is built by CI that hurdle should be gone. I mentally had "try again" on my to-do list.


As for new tips & tricks newsletters, I should probably update the sponsors page to remove mention of them. I never got any feedback about them and it was pretty demotivating to spend hours and hours writing something that in the end could be read by a maximum of ~ten people...

**Comment by bovine3dom** [comment]
https://tridactyl.xyz/newsletters/ done! :) Sorry it took so long.
