### ISSUE TITLE
Tridactyl install on Android Firefox nightly failing 

### ISSUE THREAD

**Issue by yashasolutions** [tridactyl/tridactyl#4413]
## Brief description of the problem

Installation of Tridactyl on Firefox Nightly for Android 

-   Steps to reproduce:

   1.  Using the AOM method
    - Create a collection on AOM
    - Add Tridactly to the collection
    - Select installation of Tridactyl
    - Get message that installation failed. 

   2. Using the web-ext method
    - download the latest release (1.22.1)
    - install using `$ web-ext run -t firefox-android --adb-device R9XXXXXV --firefox-apk org.mozilla.fenix`
    - get following error:
```
WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/data/local/tmp/web-ext-artifacts-1665287819161/tridactyl-1.22.1.xpi': Error: Extension is invalid
    at RemoteFirefox.installTemporaryAddon (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/firefox/remote.js:100:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async FirefoxAndroidExtensionRunner.rdpInstallExtensions (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:506:23)
    at async FirefoxAndroidExtensionRunner.run (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:87:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/extension-runners/index.js:72:5)
    at async run (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/cmd/run.js:180:3)
    at async Program.execute (file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/lib/program.js:289:7)
    at async file:///home/user/.nvm/versions/node/v16.17.0/lib/node_modules/web-ext/bin/web-ext.js:13:1

```

So, unsure if it's a bug, a version of firefox that's not compatible, or maybe not meant to work on android (even if it shows up in the AddOns store for android)...

Has anyone a working version on android? Is there anything that can be done based on the error messages I got?

Thanks!

**Comment by bovine3dom** [comment]
Hi, I don't know if it's the cause of your error but Tridactyl isn't designed to run on Android. I think we have explicitly marked it as incompatible.

You could try installing an extremely old version, e.g. something from around 2018, roughly before this issue: https://github.com/tridactyl/tridactyl/issues/849 - Tridactyl worked on Android back then (simply by chance :))

**Comment by yashasolutions** [comment]
Well that definitely explain why then :)

**Comment by Iey4iej3** [comment]
> Hi, I don't know if it's the cause of your error but Tridactyl isn't designed to run on Android. I think we have explicitly marked it as incompatible.
> 
> You could try installing an extremely old version, e.g. something from around 2018, roughly before this issue: #849 - Tridactyl worked on Android back then (simply by chance :))

Is it possible to improve the Android compatibility? Some other extensions (e.g. FireMonkey) that were not at all designed for Android work there.

The Firefox Android back then (2018) is different from what it is now.

**Comment by bovine3dom** [comment]
We would need to add checks for compatibility to our build system. Most of the issues blocking #1619 would unblock it.

I don't want to go through manually and make Tridactyl work on Android without doing that because I'm sure we would just break it again without realising.

But there's nothing fundamentally stopping us, we just need graceful fallbacks where various APIs aren't available.

**Comment by Utopiah** [comment]
FWIW I'd be interested in this. I'm typing this very message on my phone thanks to my Bluetooth keyboard which I use while traveling.

Using Firefox on Android is nice... but without Tridactyl it feels very clunky when a keyboard is available.

**Comment by bovine3dom** [comment]
@Utopiah how motivated are you? it should be a pretty simple task of going through the errors here https://github.com/tridactyl/tridactyl/pull/5215 and adding compat functions / graceful fallbacks for them

one potential showstopper is that it looks like Firefox Android doesn't support history search, so `:tabopen` completions would only get bookmarks...

**Comment by Utopiah** [comment]
I am not Android developer so if any specific target, e.g Android on ARM, requires a build environment is needed I would have to try to set that up first. I do not have Android Studio and prefer CLI.

If it is just about adb on a specific Firefox build with apk then should be quite quick to start.

Lacking history is not ideal but keyboard navigation remains useful especially as Firefox on Android does not even currently supports anything, not even open/closing tabs.

**Comment by bovine3dom** [comment]
there's no special cross compiling to do, our normal build process should work, although actually getting the extension into Firefox Android is not something i had thought about yet 

https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/ seems straightforward enough

but there's a lot of guards to add before we get there

if you want to test it i would suggest just flipping the isAndroid check so that we think your desktop is Android and run all the fallbacks

**Comment by Utopiah** [comment]
Some tests probably not done the right way : 

```

fabien@debian2080ti:~/Prototypes/tridactyl_android$ web-ext lint  | grep ANDROID
fabien@debian2080ti:~/Prototypes/tridactyl_android$ adb devices 
List of devices attached
000000FB000123 device

fabien@debian2080ti:~/Prototypes/tridactyl_android$ web-ext run -t firefox-android --adb-device 000000FB000123 
Running web extension from /home/fabien/Prototypes/tridactyl_android
Selected ADB device: 000000FB000123

Packages found:
 - org.mozilla.firefox
Selected Firefox for Android APK: org.mozilla.firefox
Stopping existing instances of org.mozilla.firefox...
Starting org.mozilla.firefox...
Waiting for org.mozilla.firefox Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
Building web extension from /home/fabien/Prototypes/tridactyl_android
Waiting for org.mozilla.firefox Remote Debugging Server...
Make sure to enable "Remote Debugging via USB" from Settings -> Developer Tools if it is not yet enabled.
You can connect to this Android device on TCP port 39333

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/data/local/tmp/web-ext-artifacts-1746648077678/tridactyl_beta-1.24.2pre7121.xpi': Error: Extension is invalid
    at RemoteFirefox.installTemporaryAddon (file:///usr/local/lib/node_modules/web-ext/lib/firefox/remote.js:94:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FirefoxAndroidExtensionRunner.rdpInstallExtensions (file:///usr/local/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:458:23)
    at async FirefoxAndroidExtensionRunner.run (file:///usr/local/lib/node_modules/web-ext/lib/extension-runners/firefox-android.js:102:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///usr/local/lib/node_modules/web-ext/lib/extension-runners/index.js:67:5)
    at async run (file:///usr/local/lib/node_modules/web-ext/lib/cmd/run.js:171:3)
    at async Program.execute (file:///usr/local/lib/node_modules/web-ext/lib/program.js:270:7)
    at async file:///usr/local/lib/node_modules/web-ext/bin/web-ext.js:13:1

fabien@debian2080ti:~/Prototypes/tridactyl_android$ 

```

**Comment by bovine3dom** [comment]
@Utopiah i have added some stuff to the manifest in that PR that should at least allow it to install

Tridactyl itself probably won't actually work because I only got about half way through adding guards on all the missing APIs :)

**Comment by Utopiah** [comment]
Starting to tinker with a minimalist alternative https://git.benetou.fr/utopiah/keyboard-extension/ without even supporting switching tabs but still something keyboard centric that works on Android at least.

**Comment by bovine3dom** [comment]
Oh cool. I had actually made good progress on https://github.com/tridactyl/tridactyl/pull/5215#issuecomment-4948060821 but then I realised that `history.search` doesn't exist on android, so `:tabopen ` completions would only be bookmarks. Then I stopped because I couldn't really imagine Tridactyl being useful without that...

If you disagree (and I guess you do if you've made your own :) ) I would be happy to have another crack at it in a few weeks

**Comment by Utopiah** [comment]
Indeed I disagree. Yes full support would be better... but even if it's only navigation on a page (even without hinting), between tabs, search within a page, search with defined engines, then it would still be better than what's possible otherwise, namely only typing content in the URL bar or going up or down with arrows.

That said it is a niche within a niche. I imagine very few people need that (hence why Mozilla itself does not bother with even the most basic shortcuts) but those who do, including me, will appreciate!
