### ISSUE TITLE
mode string shows up in printed output

### ISSUE THREAD

**Issue by larsks** [tridactyl/tridactyl#453]
Version: Tridactyl 1.9.8-3-g4d969e5

The mode string that tridactly displays ("insert", "normal", etc) shows up when printing a web page.  I was trying to figure out why my printed documents all said "normal" in apparently random places.  Now I know why.

**Comment by larsks** [comment]
The problems persists with 1.9.8-3-g4d969e5.

**Comment by cmcaine** [comment]
Sorry about that. We'll change the CSS to display:none for printed media.

**Comment by larsks** [comment]
Should this fix be in version `Tridactyl 1.12.0-16-ge547728`?

**Comment by bovine3dom** [comment]
Yes, but I think someone else said it only worked on the new tab page. I'm guessing it doesn't work elsewhere. We probably need an !important.

**Comment by wavexx** [comment]
MMh, I don't want to re-open this straight away, but I can still see the "normal" status indicator in the print preview in some pages. For instance, the preview of this page doesn't show the text of the status, but there's still an underline (which I guess is the border-bottom of the status box).

**Comment by bovine3dom** [comment]
@wavexx the fix hasn't made it out into stable, yet. Are you using one of our betas?

**Comment by wavexx** [comment]
Yes, using 1.12.0-224-g270509d. As a proof of concept, look at this page:

https://www.thregr.org/~wavexx/tmp/empty.html

It's an empty document.
Try a print preview and notice the line:

![2018-05-28t173700](https://user-images.githubusercontent.com/1017726/40621629-26a8198e-628d-11e8-9a26-51ee91b19b4e.png)

I know it's part of the status indicator because in previous releases it used to show "normal" just above it.

**Comment by wavexx** [comment]
Oh, and this only happens on FF (using 60.0.1). On Chromium I do not see this behavior.

**Comment by bovine3dom** [comment]
Tridactyl works in Chromium!?

**Comment by bovine3dom** [comment]
Also I'm about 90% sure that line is just part of Firefox.

**Comment by JulioJu** [comment]
I have the same problem. Maybe this bug should be open again ?

**Comment by phmarek** [comment]
Any idea what the problem is? Having print output broken isn't that nice...

**Comment by bovine3dom** [comment]
@phmarek it should be pretty easy to fix. Work out which element is showing (probably mode indicator) and then pattern match with e4de65f to hide it. Feel free to ask questions here or on Riot if you need a hand.

**Comment by mntns** [comment]
Did a bit of testing: The mechanism in e4de65f1267de9f79acaf6f40b65c0bfdff23a5d appears to work in the print emulation mode provided by the developer tools, but curiously not in the actual print preview/result.

Loading the print stylesheet externally with `<link media="print" ...>` instead of using the directly inserted stylesheet with `@media print` doesn't work either.

(Firefox 72.0.2, Tridactyl 1.17.1pre3588-27572a5)

**Comment by Gekkio** [comment]
Here's some more technical details. Seems like a pretty clear CSS rule priority problem, but I'm not sure what would be a good fix for this.

1.17.1pre3304-7dcf183 / Mozilla Firefox 74.0 / linux

Tridactyl attempts to hide the status indicator in print by adding `!important` rules in two places:

content.css:
https://github.com/tridactyl/tridactyl/blob/74db069ef28de9880f51417b1678be54e67aca60/src/static/css/content.css#L47

content.ts:
https://github.com/tridactyl/tridactyl/blob/7705ebf5d83ed900b831962855f9d9245610b41e/src/content.ts#L211

However, cleanslate (used by Tridactyl) also uses `!important`, and it ends up negating the effect of these print styles. If you inspect the computed styles of the `TridactylStatusIndicator` element while print media simulation is enabled, you should see something like this:

![Screenshot from 2020-03-24 09-00-44](https://user-images.githubusercontent.com/94033/77397941-3b4fa080-6daf-11ea-909c-18d6b0c9a41c.png)

The added inline style element has the *least priority*, and the `content.css` variant is ignored in print mode (probably due to a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1448507), which is marked fixed...?!), so the winning style is `display: !important block` from `cleanslate.css:167`. Therefore in print mode, the status indicator is a normal visible block element.

**Comment by bovine3dom** [comment]
Thanks. In which case #1140 might fix it

**Comment by bovine3dom** [comment]
I am wondering if this is a Firefox bug - on e.g. https://en.wikipedia.org/wiki/Hovercraft_Museum if you view the page in "print media simulation" (right click, inspector, tiny page icon in the top right), there is no mode indicator. If you go to print preview (ctrl-l, alt, f, v) it does show up.

**Comment by pjf** [comment]
Reporting in that I'm still seeing this with Firefox 80 + Ubuntu 16.04 + Tridactyl 1.20.1, but due to how infrequently I print things I don't know if it's on every page, or just some of them.

Even with the bug, Tridactyl is still the best. ♥♥

**Comment by patrickdepinguin** [comment]
I do print regularly, mostly images, and I see the 'normal' every time.
I tried ':mode disable' but it also shows a 'disable' text on printed pages.

**Comment by bovine3dom** [comment]
`:set modeindicator false` - but you'll still get a funny line at the bottom of the printed document from our command line.

**Comment by freed00m** [comment]
There is no line from command if use with `:set modeindicator false`.

I use these at `user.js` to hide all bloat info from firefox
```
user_pref("print.print_footerleft", "");
user_pref("print.print_footerright", "");
user_pref("print.print_headerleft", "");
user_pref("print.print_headerright", "");  

```

**Comment by Icelk** [comment]
For me, changing the injected CSS in the `<head>` to match `span.TridactylStatusIndicator` instead of just `.TridactylStatusIndicator` resolved it.

**Comment by bovine3dom** [comment]
Seems to work great, thanks so much for sharing the solution! People have been asking us to fix it for years :)

**Comment by JulioJu** [comment]
Thanks @Icelk
