### ISSUE TITLE
`:set tabsort mru` makes `:tabmove` behave weirdly

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4602]
Steps to reproduce:

1. use the internet a bit, make some tabs, switch between them
2. `:set tabsort mru`
3. try to move the tabs somewhere with `:tabmove`
4. ???

Sometimes the IDs seem to correspond to the MRU IDs, sometimes they don't. I don't understand what's going on.

It is probably not very useful to use `:tabmove` if you are using `:set tabsort mru` but I suspect it the same issue is breaking things in other places

**Comment by treapster** [comment]
I didn't know tabmove was a thing, but suspected there are things that will break after #4595. I tried now and in my case it works fine with any number but 1. Passing 1 causes  this error:
`Error: Type error for parameter moveProperties (Error processing index: Expected integer instead of null) for tabs.move`
But is also reproduces when passing an index of the last used tab without MRU, because the argument becomes # while it expects number.
So, i see two issues:
- Indexing of completions is MRU while the command uses absolute. We should probably teach completions/Tab.ts to always use absolute indices in case of :tabmove. Or make tabmove respect tabsort(not sure) or come up with something else.
- Selecting the last used tab in completions substitutes the real index with #. Which means we should either prevent that or teach tabmove to accept it.

Aside from completions and #, it seems to jump to correct absolute indices even with tabsort=mru. Are you having similar experience?

**Comment by bovine3dom** [comment]
Yeah, it's just the completions that are wrong; `tabmove` completes with MRU IDs but then interprets those IDs as if they were just positions.

The `#` bug exists in version 1.22.1 so it isn't your fault.
