### ISSUE TITLE
Prevent focusing omnibar on new tab / window

### ISSUE THREAD

**Issue by MichaelMackus** [tridactyl/tridactyl#4673]
Is there any way to do this? I much prefer tridactyl's dialog (e.g. when pressing "o" and "t") since it is much easier & faster to use than firefox's omnibar. However, every time I open a new tab or window firefox focuses the omnibar/url bar automatically... is there any way to disable this functionality, either in tridactyl or firefox itself?

I tried `guiset navbar none` but the cmd window said it is currently broken due to #1728

**Comment by bovine3dom** [comment]
Focus on tabs is easy if you're using ctrl-t - `:bind <C-t> tabopen` - but why don't you just use `t` directly?

I think new windows are trickier - ctrl-n is reserved by Firefox so you aren't allowed to bind to it. If you can find a bind, you need to make it load a page to get focus on the page rather than the URL bar, e.g. `:bind N winopen txti.es`.

But again in most cases it is probably easier to use `w` directly :)

**Comment by MichaelMackus** [comment]
@bovine3dom thanks... I found out if I set a custom URL for home page opening a new firefox instance doesn't focus the omnibar anymore. This is adequate for me, since like you said there are keybinds for the other actions. Thank you for the help
