### ISSUE TITLE
integrate tridactyl docs action

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#4725]
https://github.com/glacambre/tridactyl-docs

ideally it would live on tridactyl.xyz (which means I need to work out how to update that page)

**Comment by glacambre** [comment]
@bovine3dom I added a commit to tridactyl-docs to make the action build the tridactyl.xyz site along with the docs. I think you'd only need to add `docs` section [here](https://github.com/tridactyl/site/blob/56cf8c09b30f2a2833713fce629823480538da2e/config.toml#L42) in order to point to the documentation.

The only question left is where the action should be merged. I think it'd make sense to put it in tridactyl/tridactyl, so that it gets triggered on every commit to master and the docs get rebuilt. This would mean that you would have to change the github pages/domain settings to have tridactyl.xyz point to tridactyl.github.io/tridactyl rather than tridactyl.github.io/site .

**Comment by bovine3dom** [comment]
Are you sure that your action works? https://glacambre.github.io/tridactyl-docs/ gives me a 404.

I remember there being something wrong with `hugo` when I last tried to build the site manually - I think somewhere there has been a breaking change. I keep meaning to dig out an old laptop to see if I can build it on that to work out what the difference is.

**Comment by glacambre** [comment]
Yep, it works, index.html is in https://glacambre.github.io/tridactyl-docs/public/ instead of the `tridactyl-docs/` (CSS is broken for the same reason). Changing this is easy, just replace `site/` with `site/public` [here](https://github.com/glacambre/tridactyl-docs/blob/main/.github/workflows/build.yml#L47).

**Comment by glacambre** [comment]
Nice, it looks like [it's working](https://tridactyl.xyz/build/static/docs/modules/_src_excmds_.html) :partying_face: . It seems that Google hasn't found it yet, but hopefully it will eventually.

I could also try to embed Algolia in the docs if you want. Neovim did this recently and [the results](https://neovim.io/doc/) are excellent IMO. They have a free offering for open source projects and I'd be very interested in getting a little bit of experience in integrating with them :)

**Comment by bovine3dom** [comment]
That would be cool! We need to update TypeDoc eventually because it is keeping us stuck on TypeScript 3, there's a PR open - https://github.com/tridactyl/tridactyl/pull/4624 I think - so try not to make it too linked to the current version :)
