### ISSUE TITLE
Feature request: add history support in :ex command

### ISSUE THREAD

**Issue by QiangF** [tridactyl/tridactyl#4756]
1. bind M-p and M-n to go to previous and next history item, should work in search box, after "/" in normal mode.

**Comment by bovine3dom** [comment]
Arrow up and down do this already in ex-mode.

You can add your own binds with e.g. `:bind --mode=ex <M-p> ex.prev_history`

I'm not sure what you mean with `/` - that is Firefox's default quick find key, cycling through results is bound to Ctrl+G/Ctrl+Shift+G, because that is what Mozilla picked. It has nothing to do with us

**Comment by QiangF** [comment]
Thank you for the tip. How can I get the previous search text filled in the firefox "quick find" box?

**Comment by bovine3dom** [comment]
Have you tried pressing ctrl-g without the box showing? I think it will re-search the page.

I have zero control over this box though - if you want to use Tridactyl's search see `:help find`

**Comment by QiangF** [comment]
find has perfect history support, thank you!

**Comment by QiangF** [comment]
I think find can be improved with regular expression support. I really miss fuzzy match in Emacs.

**Comment by bovine3dom** [comment]
Follow #1612 if you want updates about improvements to it. I don't think anything will happen quickly, though :)
