### ISSUE TITLE
`f` does not work on google searches

### ISSUE THREAD

**Issue by thomasaarholt** [tridactyl/tridactyl#4840]
Hello! I'm on tridactyl beta `1.23.0pre6867-ff696b5c` (commit appears to date to Nov 12, three days ago), and when [I search on google](https://www.google.com/search?client=firefox-b-d&q=tridactyl), I can use `j` and `k` to scroll, but `f` doesn't work.

This is on macOS 14, latest Firefox 119.01.

I thought #4765 would fix this, but it appears not.

**Comment by bovine3dom** [comment]
Hi, those binds are in the exemplar RC file so if you used them you'll have to update them in your own RC file

The relevant lines are here https://github.com/tridactyl/tridactyl/commit/5635b91dee9ffe3f3191745ebda6e68ce9942596

**Comment by thomasaarholt** [comment]
Maybe I've misunderstood, but should I not expect `f` to work "out-of-the-box" on google.com? If I search for anything on google and press `f`, nothing happens at all. On e.g. github I get highlighted boxes with characters in order to select links or buttons.

**Comment by bovine3dom** [comment]
If you have removed your RC file, `:reseturl [the Google regex] f` should get the bind back to normal.

It does work out the box :) The RC file changes the bind so that only the search results are hinted. It's fragile and breaks every few months which is why it's hidden away in a file for advanced users

**Comment by thomasaarholt** [comment]
Thank you! That worked! For any future viewers with the same problem: `:reseturl www.google.com f` worked. 

I struggled a little, expecting there to be a `reset config` kind of function in tridactyl. Is there such a function? I did observe that even though I deleted my `~/.tridactylrc` and restarted Firefox, `f` was still not working on google for me.

**Comment by bovine3dom** [comment]
You're welcome!

`:sanitise tridactyllocal` wipes your entire Tridactyl configuration.

Tridactyl simply reads the `tridactylrc` file at startup and runs each line in it as if you typed them into Tridactyl manually. (RC stands for "run commands").

But Tridactyl has persistent storage of configuration, so if your RC file modifies your configuration, those changes will persist even if you remove or change the RC file.

It's counter-intuitive because most programs that have RC files do not have persistent configuration, so RC files feel like they are configuration.

I would like to make the persistence of configuration optional in Tridactyl so that RC files make more sense, but it would mean rewriting a fair bit of Tridactyl, so it's a low priority.

Closing this because your issue seems to be resolved :)

**Comment by thomasaarholt** [comment]
Yes, thanks for closing, I meant to do so earlier. 

Maybe my problem isn't very frequent, but the following change to the readme would have been caught by my `Cmd + F "reset"` search that I did when I first encountered this issue. [PR here](https://github.com/tridactyl/tridactyl/pull/4848).
