### ISSUE TITLE
Add Daselt layout

### ISSUE THREAD

**Issue by nameiwillforget** [tridactyl/tridactyl#4965]
I'm creating a project with a custom keyboard layout, [Daselt](https://gitlab.com/nameiwillforget/daselt) and I was hoping you could add its corresponding keyboard-layout. Here is the output of the website to record the key values:
```
{
    "KeyQ": ["p", "P"],
    "KeyW": ["u", "U"],
    "KeyE": ["\"", "\'"],
    "KeyR": [",", ","],
    "KeyT": ["q", "Q"],
    "KeyY": ["v", "V"],
    "KeyU": ["c", "C"],
    "KeyI": ["l", "L"],
    "KeyO": ["m", "M"],
    "KeyP": ["f", "F"],
    "BracketLeft": ["j", "J"],
    "KeyA": ["h", "H"],
    "KeyS": ["i", "I"],
    "KeyD": ["e", "E"],
    "KeyF": ["a", "A"],
    "KeyG": ["o", "O"],
    "KeyH": ["d", "D"],
    "KeyJ": ["t", "T"],
    "KeyK": ["r", "R"],
    "KeyL": ["n", "N"],
    "Semicolon": ["s", "S"],
    "IntlBackslash": ["?", "?"],
    "KeyZ": ["k", "K"],
    "KeyX": ["y", "Y"],
    "KeyC": ["x", "X"],
    "KeyV": [".", "."],
    "KeyB": ["`", ""],
    "KeyN": ["b", "B"],
    "KeyM": ["g", "G"],
    "Comma": ["z", "Z"],
    "Period": ["w", "W"],
    "Slash": ["!", "!"]
}
```

**Comment by bovine3dom** [comment]
Hi, thanks for filing this issue. I'm happy to add it in principle, but are you expecting other people to potentially want to use it as well, or is it only for your personal use? If it is just for yourself, you can add it to your own config with `keyboardlayoutoverrides`

e.g.

```
set keyboardlayoutoverrides KeyQ pP
set keyboardlayoutoverrides KeyW uU
" etc.
```

You can also stick that in e.g. gist for use with `:source --url` if you want to get feedback from a few people first.

**Comment by treapster** [comment]
Minor nits: you have an empty case for capital B: ```"KeyB": ["`", ""]```. And there is BracketLeft but no BracketRight.

Also, while i of course don't mind what layouts users add and use, i'm just curious what's the point of adding custom layouts for shortcuts, given that default shortcuts are optimized for qwerty. For example, if you switch to that layout in tridactyl, then instead of ergonomic `j`/`k` for scrolling with index/middle finger, you'll apparently need to press left bracket in the upper right of the keyboard (mapped to `j`) and Z in the lower left of the keyboard mapped to `k`. The same applies to other shortcuts: most of them are likely to become rather uncomfortable. You could of course rebind stuff to new characters which correspond to the same old keys, but it's the same as using qwerty but with more steps. So, I'm just wondering why do you want to make tridactyl aware of your custom layout?

**Comment by bovine3dom** [comment]
That's a good point - the idea of `keyboardlayoutforce` is to make Tridactyl shortcuts be in their normal ergonomic(ish) positions no matter which keyboard layout you are using on your PC. The layout switch is just there in case you have memorised the keys in a non-US-qwerty layout.

It's great for me when I switch to a layout like `bepo` temporarily because all the keys for Tridactyl stay the same.

What are you hoping to achieve with it? It would be useful for someone uses Daselt and Tridactyl for years and builds up muscle memory for where j/k are for scrolling. They want to switch back to qwerty for a while but don't want the binds they made for Daselt change so they use keyboardlayoutforce and set keyboardlayoutbase to Daselt. 

> I could also put the layout into that file, I don't know what's better.

Personally, I'd recommend doing that for now if you want to change it somewhat often. Otherwise it will only get updated with Tridactyl releases which generally happen 2-4 times a year unless something is extremely broken.

**Comment by nameiwillforget** [comment]
> Minor nits: you have an empty case for capital B: `` "KeyB": ["`", ""] ``. And there is BracketLeft but no BracketRight.
> 
> Also, while i of course don't mind what layouts users add and use, i'm just curious what's the point of adding custom layouts for shortcuts, given that default shortcuts are optimized for qwerty. For example, if you switch to that layout in tridactyl, then instead of ergonomic `j`/`k` for scrolling with index/middle finger, you'll apparently need to press left bracket in the upper right of the keyboard (mapped to `j`) and Z in the lower left of the keyboard mapped to `k`. The same applies to other shortcuts: most of them are likely to become rather uncomfortable. You could of course rebind stuff to new characters which correspond to the same old keys, but it's the same as using qwerty but with more steps. So, I'm just wondering why do you want to make tridactyl aware of your custom layout?

Well, I've already rebound most of the shortcuts anyway. The issue are the symbols used for following links and selecting things. These are optimized for qwerty, meaning j, f, d, k and so on appear first. I thought this was the only way to change this.

**Comment by treapster** [comment]
> Well, I've already rebound most of the shortcuts anyway. The issue are the symbols used for following links and selecting things. These are optimized for qwerty, meaning j, f, d, k and so on appear first. I thought this was the only way to change this.

AFAIK the layout setting does not affect how hints are generated, but you can change it with `set hintchars`.

**Comment by treapster** [comment]
But assuming you're familiar with qwerty and have no issue mentally separating "whatever for typing, qwerty for shortcuts and hints", you don't have to change neither `keyboardlayoutbase` nor `hintchars` and everything will be ergonomic out the box(after `keyboardlayoutforce` is set). On the other hand, if you want to have a single frame of reference, then it makes sense to rebind and change everything, although it'll probably result in using the same physical keys for the same commands.

**Comment by nameiwillforget** [comment]
Ah, thanks, I guess `set hintchars` was what I was really looking for!
