### ISSUE TITLE
Server-side React renderer vandalises Tridactyl

### ISSUE THREAD

**Issue by thepragmaticmero** [tridactyl/tridactyl#5050]
-   Brief description of the problem:
I don't have access to Tridactyl inside ChatGPT even with "run on sites with restrictions" enabled

-   Steps to reproduce:
![Screenshot From 2024-09-16 09-49-57](https://github.com/user-attachments/assets/899ce9d7-eb87-4b52-a425-093458fc9094)
-   Tridactyl version (`:version`):
1.24.1

-   Firefox version (Top right menu > Help > About Firefox):
130.0

-   URL of the website the bug happens on:
chatgpt.com

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):
[tridactylconfig](https://gist.github.com/thepragmaticmero/fee3b6563d491734a63c915255b71e1b)

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
nah
```
### I'm mainly looking for answers Q-Q, also to shed light on this issue. I always go search inside the repo's issues for help on known problems.
Edit: I also should point out, the "normal" indicator at the bottom right shows for a fraction of a second and then disappears.

**Comment by bovine3dom** [comment]
There are a few websites that do this, usually we can't do anything about it. I've not looked at chatgpt specifically yet. 

Are you aware of the ctrl+comma bind that should get you to a tab where Tridactyl works?

**Comment by bovine3dom** [comment]
I've just checked and it's the same issue that I saw on another site a few days ago

It must some new thing introduced by React where if server-rendered HTML doesn't match the client (because, for example, you have extensions running), it throws a tantrum, deletes all the HTML and re-renders it on the client.

I've opened a pull request which "fixes" it for the iframe only but in a pretty dumb way that will use some CPU cycles, so it shouldn't be left to run in the background on all websites. I'm hoping we can find a better solution now we know what the problem is.

**Comment by thepragmaticmero** [comment]
Best title ever tho. Yeah JS world makes me wanna cry sometimes.

**Comment by mesaprotector** [comment]
I don't know how to check whether it's the same JS issue (if it isn't, let me know and I'll post a separate report), but most pages on Intel's website are the same way; no response from Tridactyl, and Ctrl+comma just re-renders the same page.

**Comment by bovine3dom** [comment]
Fixed in #5053

**Comment by bovine3dom** [comment]
Issue seems to have re-emerged on https://www.opensourcealternative.to/alternativesto/davinci-resolve :(

**Comment by Rhys-T** [comment]
@bovine3dom I just ran into this (or something very similar) on [the Shopify GraphQL documentation site](https://shopify.dev/docs/api/admin-graphql). The page re-renders itself, causing Tridactyl to disappear, and logs a 418 error (["Hydration failed because the server rendered HTML didn't match the client."](https://reactjs.org/docs/error-decoder.html?invariant=418)). The reason I noticed it is that it doesn't even re-render correctly: some of the CSS seems to get lost, so icons disappear, links end up looking like normal text, modals are transparent, etc. (They visibly render correctly for a moment, then break during the re-render.) If I disable Tridactyl and reload the page, it comes up fine.

Tridactyl (No New Tab) 1.24.2pre7121-f1156d5c, on Firefox 136.0.2 on macOS 10.15.7.

**Comment by bovine3dom** [comment]
General troubleshooting is:

try `:seturl ... noiframe true` to kill the command line (reload)

if that doesn't work `:seturl [awful website] superignore true` to totally disable Tridactyl on that URL



Whereas if the site renders fine but Tridactyl doesn't work, run

`seturl ... commandlineterriblewebsitefix true`

---

@Rhys-T if you're a Shopify customer maybe you would like to express your disappointment that they're using such user-hostile software :)

**Comment by Rhys-T** [comment]
`noiframe` seems to keep it from re-rendering.

It seems to have just started this recently. Not sure what they changed. It looks like basically the same site as before, so I don't think they just added React or anything…

I'll try to mention this issue to Shopify support at some point, but honestly I have other things I need them to work on first :)

**Comment by bovine3dom** [comment]
My understanding is that it's a relatively new anti-feature in React/Next.js

Everyone updated Next.js in a mad panic at the weekend because it turned out if you asked it to bypass all authentication it would happily bypass all authentication https://github.com/advisories/GHSA-f82v-jwr5-mffw

**Comment by Rhys-T** [comment]
> […] if the site renders fine but Tridactyl doesn't work, run
> 
> `seturl ... commandlineterriblewebsitefix true`

Just realized I misread this before, and thought it was for the case where `noiframe` _didn't_ help.

I just tried `commandlineterriblewebsitefix true` on the Shopify dev site. It does bring back the Tridactyl mode/status indicator badge, and the basic keys (<kbd>j</kbd>/<kbd>k</kbd> and such) seem to work. However, the `iframe` still doesn't seem to work: it's nowhere to be seen in the devtools, and if I hit <kbd>:</kbd>, it throws `TypeError: cmdline_iframe.contentWindow is null` and doesn't open the command line - and then all the other keys stop working until I reload the page. Even the builtin shortcuts like <kbd>⌘L</kbd> and <kbd>⌘K</kbd> stop doing anything at that point, at least while focus is in the document.

**Comment by Chic-Tweetz** [comment]
For some Reacty reason the `documentElement` is replaced on those sites. At least on https://www.opensourcealternative.to/alternativesto/davinci-resolve page, there's a call to `document.removeChild(document.documentElement)` which I suspect is why the iframe disappears.

When you press `:` I think the key parser gets stuck in a "buffer keys for iframe" state, but the iframe never even gets to load so it can't send any messages to let key presses work again.

The good news is that at least for that page and the [shopify](https://shopify.dev/docs/api/admin-graphql) link, the `documentElement` is replaced between `document.readyState` `"interactive"` and `"complete"` so adding a listener to check the iframe still exists after it's `"complete"` lets us add it back to the page if necessary.

I added a function to check the iframe's `isConnected` property and put it back on the page if it's false. I've put it in a `"readystatechange"` listener, as well as the `show` command and it seems to be working. [Related pull request.](https://github.com/tridactyl/tridactyl/pull/5260)
