### ISSUE TITLE
Search bar focus broken

### ISSUE THREAD

**Issue by luntik2012** [tridactyl/tridactyl#5088]
After installing `firefox-tridactyl` and `firefox-tridactyl-native` and switching back to "Blank page" new tab I have address bar focused instead of search bar. "ctrl+t" should open new tab and focus on search bar. To focus on address bar we can use "ctrl+l" or disable search bar.
Removing tridactyl doesn't help.

**Comment by bovine3dom** [comment]
> Removing tridactyl doesn't help.

I don't think this has anything to do with Tridactyl :)

1. Make a fresh Firefox profile with `firefox -P`
2. Hamburger menu -> More Tools -> Customise Toolbar -> (drag search bar onto menu)
3. Ctrl+t gives focus to the address bar

I'd suggest asking on the Firefox support forums/IRC and maybe filing an issue on Bugzilla if it turns out to be a bug

**Comment by bovine3dom** [comment]
I understand where you're coming from - from what you've described using Tridactyl could be the cause of it.

But I don't think it's intended behaviour from Mozilla, it is probably a Firefox bug that installing an extension can change address/search bar focus, so if you want it fixed it's best to talk to them :)
