### ISSUE TITLE
Lightweight analytics (no, not google or any third party)

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#509]
At the moment, we have very little idea who uses the beta builds. Mozilla give us quite [nice statistics](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/statistics/?last=30) about the stable releases.

A simple first step would be to log the number of requests to update.json on tridactyl.cmcaine.co.uk/betas via https://caddyserver.com/docs/log.

I have something of a soft spot for weird squiggly graphs, so it would be pretty cool to have something more complicated later on, perhaps measuring excmd usage / proportion of pages opened using Tridactyl vs not, the values of various settings, but anything really contentious would be opt-in, and the less contentious stuff (like "Tridactyl is enabled") would be opt out.

**Comment by glacambre** [comment]
I don't know much about it but if you want to comply with the [GDPR](https://en.wikipedia.org/wiki/GDPR) you'll probably need to make this opt-in.

**Comment by bovine3dom** [comment]
I've started logging stuff like I said I would, stored in public_html/../caddylog (i.e, not publicly accessible).

A reasonable guess at the number of daily users of the beta is `cat caddylog | grep "GET /betas/updates.json" | grep $(date -d '-1 day' +"%d/%b") | wc -l`.

So far we have 9.

It would be nice to have a script that generates graphs from this automatically and hosts it on the web server; it would be a great excuse to get some Julia code into this repository.

**Comment by bovine3dom** [comment]
https://blog.mozilla.org/addons/2016/05/31/using-google-analytics-in-extensions/ has a tiny little guide on getting Google Analytics set up via POST (which we will not be doing).

It looks like https://matomo.org/ offers a similar, self-hosted service. I'm not sure I want to set it up so that my own machine gets DDOS'd by Tridactyl users, though, so we might have to think about some other solution.

**Comment by glacambre** [comment]
>interestingly, Firefox + Tridactyl's CPU usage goes through the roof on that matomo page

This is not caused by Tridactyl. According to the performance tab of Firefox's console, CPU usage comes from constantly recomputing styles and this happens with and without Tridactyl.

**Comment by wavexx** [comment]
Just to reply to a previous message, as I had to deal with GDPR recently for another project (https://github.com/DownloadTicketService/dl/) you'd be surprised in what constitutes a violation.

The IP address, implicitly coming from the request, is already personal data. The remote IP address stored in a web server log in front of your service already *requires* a GDPR statement that you need to show to your users and needs to be "clearly stated and easily accessible", even if the address is stored sorely for the purpose of debugging and is not shown and/or used otherwise, let alone for statistical purposes.

As the law is written in a super-general form, I'd say it's almost impossible to bypass the requirement of at least the GDPR statement if the request hits a web server under your own control. You'd need to discard almost anything *before* performing the request, and discard any detail about the request *at* the time of the request in order to be compliant.

I'd stay kilometers away from doing anything "opt-out".

**Comment by wavexx** [comment]
I had a thought about this to store hashed IP addresses in logs, but as I understood the argument between the lines, any hashing scheme wouldn't change anything from this perspective. If you can reliably perform the same trasformation (IP -> hash) in a reliable way that can be performed later, there's no difference since you can *still* comply with a data request.

**Comment by bovine3dom** [comment]
> you can still comply with a data request

Surely only if they can prove that the IP address is theirs at the times they want it? Otherwise I'd just be handing it out to random people.

**Comment by wavexx** [comment]
Of course. But that doesn't matter for compliance. One needs to prove that, which is hard, but law enforcement certainly can force you.

It's quite annoying really, and the solution proposed by caddy is actually the right one: simply chop the data so that info isn't there at all.

For example, in my case, I simply send out a link to people which result in a prompt to download. I'm not even sure I can ever be compliant unless I add one of those annoying prompts before the download. On the other hand, if I trim the data and I'm also at loss when trying to diagnose problems as a sysadmin. There's no win-win here, and I consider this to be a huge oversight in the law.

**Comment by bovine3dom** [comment]
Closing this issue as I don't think we'll get much value from it.
