### ISSUE TITLE
Cannot make `gi` pass through to gmail

### ISSUE THREAD

**Issue by dradetsky** [tridactyl/tridactyl#5091]
Tridactyl version: 1.24.1
Firefox version: Mozilla Firefox 132.0.2
Operating system: linux

-   Brief description of the problem:

I want to unbind `gi` when using gmail, since it's the native gmail keybind for "go to inbox". Other unbinds work fine in gmail, I was able to add the following:

```
unbindurl mail.google.com/mail j
unbindurl mail.google.com/mail k
```

and now gmail's native j/k binds will select next/prev msg. However, adding the following:

```
unbindurl mail.google.com/mail g
unbindurl mail.google.com/mail i
unbindurl mail.google.com/mail gi
```

will not allow `gi` to pass through and take me back to the inbox (note: I added the other 2 unbinds in case they were relevant, but I don't actually care about them).

-   Steps to reproduce:

See above

-   URL of the website the bug happens on:

See above

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):

See above

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

See above

```
Insert tridactylrc contents between the backticks
```

**Comment by Chic-Tweetz** [comment]
`unbindurl ...` does unbind `focusinput`, but gmail only gets the `i` key press because there are other Tridactyl key sequences that begin with `g`

You could try something like `bindurl mail.google.com/mail gi open https://mail.google.com/mail/u/0/#inbox`

If you use multiple gmail accounts, I believe the `/u/0/` part would have different numbers for different accounts. You could let the gmail keybinds sort it out in that case:

`bindurl mail.google.com/mail gi js document.dispatchEvent(new KeyboardEvent('keydown',{key:'g'})); document.dispatchEvent(new KeyboardEvent('keydown',{key:'i'}))`

**Comment by dradetsky** [comment]
@Chic-Tweetz I suspected that (i.e. the existence of binding to `gf` or whatever) was the cause, although it's interesting that gmail receives just the `i`. I wouldn't have guessed that, and it certainly seems undesirable and likely to lead to unintended behavior (although FWIW I haven't actually validated that it's what happens).

In any case, your proposed 2nd example does work for me. Interestingly, it's related to the kind of solution/debugging-method I wanted to use in this case. However, it seems a bit on the wordy side.

If I were to suggest we implement an excmd `send_keys $str` which basically just does the `document.dispatchEvent()` bit for each char of `$str`, what would be the downside?

**Comment by dradetsky** [comment]
Okay, I've decided the `send_keys` idea is silly, and PR'd an example config that might be of interest to future users (#5095). I _think_ this is solved, but I'll let @bovine3dom make decision.

**Comment by Chic-Tweetz** [comment]
@dradetsky it is a wordy one :) I don't think a `send_keys` sounds too silly. Sort of a `keyfeed` but for the page instead of Tridactyl.

I suspect `document.dispatchEvent(...)` wouldn't work in all cases, eg if a page checks the `isTrusted` property of the event. So something more clever would be in order.

I agree it's counterintuitive that only the last letter in a key sequence is passed to the page, I guess Tridactyl consumes the other key events in checking for bindings.

**Comment by dradetsky** [comment]
@Chic-Tweetz the reason I decided it was silly is that I took the extra 15s to realize I could instead write

```
bindurl mail.google.com/mail gi js [...'gi'].\
forEach(c => document.dispatchEvent(new KeyboardEvent('keydown',{key: c})))
```

which is good enough. Like, it's ugly, but not ugly enough that I think somebody needs to do any actual (_retches audibly_) programming.

**Comment by dradetsky** [comment]
Having posted this, I think this is solved now: https://github.com/tridactyl/tridactyl/wiki/Exemplar-.tridactylrc-files#dmrs-gmail-example
