### ISSUE TITLE
Open in external editor is slower than it used to be. I think.

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#512]
I suspect this is because we're doing quite a few calls to getNativeMessengerVersion().

Suggested solution: move version checking to the python script:

- bin native gate and instead have reqVersion component to messages, so it gets done for free
- messenger returns non-zero exit code and actualVersion if the version is wrong.
- friendly message to user
- bin nativegate() and semver-compare

Edit:
- check to see if I live in a goldfish bowl

**Comment by glacambre** [comment]
We could also keep a persistent connection to the native messenger instead of starting a new one every time. This would make updating the native messenger a bit more complicated but we'd be free of python's slow startup times.
```sh
time printf '0\0\0\0{"cmd": "version"                      }' | ~/.local/share/tridactyl/native_main.py
```
Takes 0.04 seconds on my computer.

This could also let us implement some sort of RPC mechanism where you could send commands to tridactyl from your shell, a bit like you can send messages to i3 thanks to i3-msg. I'm not sure this feature would be useful though.

**Comment by bovine3dom** [comment]
Related - we should have a special return code for unhandled messages and listen / catch that rather than bothering with `nativegate` for cases where a new `cmd` has been added.

**Comment by bovine3dom** [comment]
Fixed with nim messenger
