### ISSUE TITLE
Thwart the stupid tiny muted exclamation mark when Tridactyl asks for more permissions

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#708]
We can get an RSS version feed from https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/format:rss, so we can presumably just shove something on the new tab page that notifies people that there's a new version available, and gives them a link to the new version on the AMO.

**Comment by bovine3dom** [comment]
Yeah, we can put any file we want there. We'd need to generate our own RSS time obviously though.

It's probably easier to just use the update.json now I think about it. I don't know where it lives on the AMO but it must be somewhere.

**Comment by glacambre** [comment]
Actually, the new tab page might not be the best place for this since users can choose to use something else. Perhaps the statusline is a better place for this (once it's implemented, that is)?

**Comment by glacambre** [comment]
Looks like [a third of Tridactyl users are still using an old Tridactyl version](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/statistics/usage/versions/?last=30). Once the update mechanism discussed here is implemented, we should probably temporarily turn all the new permissions Tridactyl requires since 1.7 into [optional permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/request) so that Firefox will silently upgrade Tridactyl.

**Comment by bovine3dom** [comment]
> we should probably temporarily turn all the new permissions Tridactyl requires since 1.7 into optional permissions so that Firefox will silently upgrade Tridactyl.

That's not possible: most of the permissions we need can't be optional.

We could potentially release a really pared down Tridactyl that doesn't need any of the new permissions, but that might upset the two-thirds of people who are on a recent version.

**Comment by glacambre** [comment]
>most of the permissions we need can't be optional.

Do you mean that Tridactyl fundamentally needs them to work, or that Mozilla doesn't provide a way to make these permissions optional? If it's the latter what am I misunderstanding in the following paragraphs?

[permissions.request()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions/request):
>Ask for the set of permissions listed in the given permissions.Permissions object.
>The Permissions argument may contain either an origins property, which is an array of host permissions, or a permissions property, which is an array of [API permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#API_permissions), or both.

[API permissions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#API_permissions):
>API permissions are specified as keywords, and each keyword names a WebExtension API that the extension would like to use.
>The following keywords are currently available:
>- [...]
>- browsingData
>- [...]
>- contextualIdentities
>- cookies
>- [...]
>- downloads
>- [...]
>- nativeMessaging
>- [...]

I've only listed the new permissions Tridactyl requires since 1.6.1 but I believe every permission is available.

**Comment by glacambre** [comment]
I wasted half an hour implementing an update mechanism based on [browser.runtime.requestUpdateCheck()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/requestUpdateCheck) before realizing that it wasn't supported by Firefox.


The update json lives here for AMO:
`https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=tridactyl.vim@cmcaine.co.uk&version=null&maxAppVersion=null&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=62.0a1`
I removed all unnecessary parameters from the url but we'll still need to figure out how to fill appID (it's a UUID but replacing it with Tridactyl's installation UUID doesn't seem to work) and appVersion.
