### ISSUE TITLE
Private windows and newtab changelog "new features"

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#749]
Our little red notification appears every time you open a new private window and view our newtab page.

**Comment by glacambre** [comment]
That's because localstorage isn't saved in private windows. And this makes me realize that it isn't either in containers.

The only solution I can think of is to replace localstorage with the browser.storage but storing information about whether the changelog has been seen in the config feels very wrong. I don't know what else we could though.

**Comment by bovine3dom** [comment]
I was going to suggest just never displaying the message in a private window :)

**Comment by glacambre** [comment]
Should we also never display it in new tab pages in containers?

**Comment by bovine3dom** [comment]
Maybe. I don't think it will be as obvious.
