### ISSUE TITLE
One of the plugins on the atom editor seems to be doing well, so can we learn from it

### ISSUE THREAD

**Issue by linjialiang** [tridactyl/tridactyl#773]
> One of the plugins on the atom editor seems to be doing well, so can we learn from it

**The project address** [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus.git)

**Comment by glacambre** [comment]
You seem to be familiar with this project, what exactly can Tridactyl learn from it?

**Comment by linjialiang** [comment]
> This project is a vim schema plug-in above the atom editor
> - It's much more powerful than the vim mode of other editors, and it implements a lot of vim tricks!
> - Of course, I'm not sure this project will help you. I just want to give you some help!
> - If you want to try it out, you can use the `atom editor` and install the `vim-mode-plus` plug-in

**Comment by glacambre** [comment]
>It's much more powerful than the vim mode of other editors

Sure, but what features does it have that you would like to see implemented in Tridactyl? What are the vim tricks you would like to be able to use?

>I just want to give you some help!

Thank you :)

I don't have enough time to install atom, its vim mode and try to discover which of its features would be a great fit for Tridactyl, that's why it'd be very helpful if you told us what you think should be copied from vim-mode-plus :).

**Comment by bovine3dom** [comment]
Hi @linjialiang,

Are you suggesting that we make a vim-style text editor in Tridactyl for editing text?

I've lost interest in that idea since if you have `:native` installed you can press Ctrl-i to edit the text in your chosen editor. If you want to edit in atom you can use `set editorcmd atom -w`.

Making our own text editor seems like it could be a lot of work, but we do have an issue open for it at #108.

**Comment by glacambre** [comment]
I'm closing this for now, if there's anything you'd specifically like us to implement in Tridactyl feel free to let us know here or to open a new issue :)
