### ISSUE TITLE
Compiled executable is much slower than python script

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#787]
Steps to reproduce:

1. Have python 3 installed
2. Run :installnative in powershell
3. Run :native in Tridactyl, observe how it is almost instant
4. Rename C:\Windows\py.exe to something else
5. Run :installnative in powershell
6. Run :native in Tridactyl, observe how it takes quite a few seconds

**Comment by Susexe** [comment]
I can confirm this too. Running **vim.exe** with Python script takes ≈1 second compared to .exe's ≈3.

**Comment by gsbabil** [comment]
@bovine3dom @Susexe

#### ## TL;DR

1. Lets reduce number of round-trips between JavaScript and Python

2. Lets move to a language with better start-up time and
   cross-platform build support as compared to Python for native
   messaging


#### ## Further Details

I think the primary contributor to this delay is coming from the
following:

1. The way `PyInstaller` works _i.e._ how it compiles/packs the
   Python script into an EXE

2. The way we are using the `PyInstaller` compiled EXE _i.e._ every
   time the EXE is invoked, it needs to be unpacked first, and then
   executed _etc._

3. I think we are also missing out on the opportunity to use the
   cached Python byte-code _i.e._ `__pycache__/*.pyc` files when
   invoking the EXE, since it unpacks to unique temporary directory
   each time _e.g._ `C:\Users\VVV\AppData\Local\Temp_MEI24082\`.

4. Some of the Tridactyl "native" commands require multiple
   round-trips with the `native_main.{exe,py}` costing extra time.

    - IMHO, the JavaScript code should send the target
      native-message to the Python (native-messenger binary) world,
      let the complexity to be handled there, consume the returned
      value, and pass it on to the Tridactyl user.

    - This will essentially lead to 1 round-trip between JS and PY
      (native-messenger binary), potentially leading to less delay
      and better UX.

    - Currently, we are not doing it for all native messages. For
      example, to invoke the editor, we exchange as many as 5 native
      messages as shown below, leading to the invokation of
      `native_main.{py,exe}` at least 5 times before some before the
      successful launch of the editor:

```
18:36:12 PM {'cmd': 'version'}
18:36:12 PM {'cmd': 'temp', 'content': 'lorem ipsum', 'prefix': 'github.com'}
18:36:13 PM {'cmd': 'run', 'command': 'where gvim'}
18:36:13 PM {'cmd': 'run', 'command': 'gvim -f C:\\Users\\user\\AppData\\Local\\Temp\\tmp_github.com_2cdtjcsi'}
18:36:20 PM {'cmd': 'read', 'file': 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp_github.com_2cdtjcsi'}
```

Essentially a big UX cost is coming from Python's start-up time,
specially when it's compiled to an EXE with PyInstaller, and our
sub-optimal way of exchanging native-messages with the
native-messenger binary _i.e._ `native_main.{py,exe}`.

I think for "native-messaging", we should explore other performant
languages with better cross-platform build support, and avoid VM
based languages.

My rationale for this is that with a VM based language, we are
loading the whole VM irrespective of the code we are interested in
running _i.e._ `native_main.py`. Since we invoke `native_main.*`
frequently, each time we exchange a `native-message`, things will be
much faster if we have compiled native/machine-code, rather than VM
based byte-code.

Another alternative could be if we perform "native-messaging" as
network IO _i.e._ `native_main.*` listens on a given network port
_e.g._ 57896, and we exchange messages with the daemon listening on
57896 whenever "native-messaging" is required.

Hope this helps. Thanks.

**Comment by bovine3dom** [comment]
My plan for speeding this up was to move to a daemon (i.e, option 2). We have another issue #512 for general native messenger performance enhancements.

**Comment by bovine3dom** [comment]
Fixed with nim messenger
