### ISSUE TITLE
`D` gives error if only a single tab open

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#918]
`# TypeError: (intermediate value)[1] is undefined `

**Comment by glacambre** [comment]
That's because D is `composite tabprev; sleep 100; tabclose #` and you can't `tabclose #` if `#` is already closed. Not sure how we should fix this. Maybe we could just bind `D` to `jsb browser.tabs.query({active: true, currentWindow: true}).then(tabs => tri.excmds.tabprev().then( _ => tri.excmds.tabclose(tabs[0].index + 1)))` ?

**Comment by glacambre** [comment]
What should `tabclose #` do when there's only one tab open? Should it close the current tab or error out?
