### ISSUE TITLE
Need equivalent to `unbind` for other settings

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#929]
As glacambre mentioned in #921:

> Actually we probably need something more general than just renaming the bindings in config. We have the same problem with searchurls, if you unset searchengines.google, running open google is evil will still search for is evil on google :/

**Comment by saulrh** [comment]
`searchsetkeyword google google %s` is *almost* a workaround, but command-line lexing means it's one character off:

`open google foo bar` -> opens `googlefoo bar` instead of opening `google foo bar`.

I can't quite complete the hack, but that might just be because I'm not familiar with the command system.

**Comment by glacambre** [comment]
This can be emulated by using something that can't be turned into an URL as value, e.g. `set searchurls.google ""`. Since Tridactyl will fail to convert `""` into an url [here](https://github.com/tridactyl/tridactyl/blob/master/src/excmds.ts#L515), it will fall back to using `searchengine`, which you can configure to be whatever you want.

**Comment by glacambre** [comment]
My `set searchurls.google ""` hack doesn't work anymore, probably because of my searchengine-enabling PR :(

**Comment by bovine3dom** [comment]
Have you made sure you've deleted the engine from FF, if that's even possible?

**Comment by jamesblau** [comment]
@bovine3dom, do you mean removing the engine from about:preferences#search? That doesn't seem to have an effect.

**Comment by universknight** [comment]
can we just have no default searchurls?
people can set their own if they need it

**Comment by bovine3dom** [comment]
`:setnull searchurls.google` : )
