### ISSUE TITLE
viewconfig --but-only-things-i've-changed

### ISSUE THREAD

**Issue by lartaud** [tridactyl/tridactyl#98]
Hello!
* I think it would be very useful to have a way to list the active bindings.
This list should have a flag telling if the binding is custom or factory, and ideally if it is a custom rebind of a factory one.
The function should accept a parameter to filter on one key, so that users can easily know if the binding they are about to create will overwrite another one… It should prevent some confusions…
* Some sort of “reset ALL bindings to factory defaults” panic function should probably be a good idea, too…

**Comment by bovine3dom** [comment]
Re point 2: it's probably possible to unbind the command line from `:`, so we should probably make sure a reset button is available on the extension settings page, once that arrives.

**Comment by holtzermann17** [comment]
The documentation (via `:help`) says at the top: "The default keybinds can be found **here**."  But after following the linked word "here" to `moz-extension://07b39b24-4362-4cd6-81c2-d5e22bad00e5/static/docs/modules/_parsers_normalmode_.html#defaultnmaps` I don't see anything about keybindings.  Perhaps that line should be commented out until this issue is resolved.

**Comment by bovine3dom** [comment]
Oh, wow. I thought I had fixed that.

Keybinds are viewable in config.ts and its help file.

**Comment by holtzermann17** [comment]
Thanks! It looks like someone has started to make some narrative documentation here, as well: https://github.com/cmcaine/tridactyl/blob/master/doc/amo.md

**Comment by bovine3dom** [comment]
This is mostly done, now:


> I think it would be very useful to have a way to list the active bindings.

`viewconfig nmaps`

> This list should have a flag telling if the binding is custom or factory, and ideally if it is a custom rebind of a factory one.

`viewconfig` without nmaps shows you only user-bindings under nmaps because of a ~~~bug~~~ feature.

> The function should accept a parameter to filter on one key, so that users can easily know if the binding they are about to create will overwrite another one… It should prevent some confusions…

`viewconfig` has a search box, is that good enough?

> Some sort of “reset ALL bindings to factory defaults” panic function should probably be a good idea, too…

`unset nmaps`. If you manage to unbind `:`, you can still do this by going to the new tab page, opening the web console with `<C-S-k>` and typing `tri.excmds.unset("nmaps")`... but we should probably include a button as part of #502.

I'll leave this open for the `viewconfig --but-only-things-i've-changed` option.

**Comment by bovine3dom** [comment]
There has been a `reset` button in Tridactyl for a while - `:help nmaps<CR>G`, click the button. Also accessible from `about:addons` if you click on "Preferences" (if you use Linux) or "Options" (if you use Windows) under Tridactyl and scroll to the bottom of the page.

**Comment by willsALMANJ** [comment]
In case anyone else ends up here and wonders what happened to `viewconfig --but-only-things-i've-changed`, it ended up being implemented as `viewconfig --user`.
