### ISSUE TITLE
Some keybinds do not work on specific keyboard layouts

### ISSUE THREAD

**Issue by tomaskallup** [tridactyl/tridactyl#983]
*   Brief description of the problem:
I'm on Mac with a Czech keyboard, where for example to type `;` I need to use `Alt + ů` (`ů` is next to `k`), and I'm unable to use some keybinds. Among them is `;k` and all the ones starting with `;`. 
I've also tried to bind `<<` to tabmove -1 and that doesn't seem to get recognized.
Is there any way to debug it, for example log on screen the current key I'm pressing?
*   Tridactyl version (`:version`):
1.13.3-1.13.3
*   Firefox version (Top right menu > Help > About Firefox):
61.0.2 
*   URL of the website the bug happens on:
Any website
*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/tomaskallup/bd3a7056a40c38821b55d9438e957ba2
*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
None

**Comment by glacambre** [comment]
Hi, thank you for opening this issue. A pull request that should help with different keyboard layouts has been merged recently, I think you could try to run `:keymap <A-ů> ;` in order for `<A-ů>` to be interpreted as `;` by Tridactyl. This might be only available in the [betas](https://tridactyl.cmcaine.co.uk/betas/tridactyl-latest.xpi) though, so you would need to switch to that.

**Comment by bovine3dom** [comment]
We just added `keymap` in 1.14.0, could you try that? E.g. `keymap û :` #980.

**Comment by tomaskallup** [comment]
If I do `keymap ů ;` that seems to work, but it works for `ůk`. However doing `keymap <A-ů> ;` didn't seem to do anything 😕

**Comment by bovine3dom** [comment]
Yeah, keymap is for dumb keys to other dumb keys, @glacambre was wrong I think :)

What does "it works for uk" mean? Is that not what you wanted?

**Comment by tomaskallup** [comment]
I was hoping to get the actual `;k` to work, which for me is `<A-ů>k`. But I guess this is good enough, I wouldn't use `ů` anyway.

**Comment by bovine3dom** [comment]
Ah, I see. I'll open another issue.

**Comment by saulrh** [comment]
I think that we might be able to handle it, actually? It'd just be... kind of disgusting, and I've totally failed to come up with concise, usable names for things.

Add another map in the config that looks like this:
```vimscript
keymap ů u
keymapwithmodifiers <A-ů> ;
```
Implement `keymapwithmodifiers` with a line of code like this, since config.set does some fancy recursive things:
```typescript
set(keytranslatemapwithmodifiers, source, target)
```
Then change the inside of `translateKeysUsingKeyTranslateMap` to something like this:
```typescript
        const newspecifickey = keytranslatemapwithmodifiers[keyEvent.toMapstr()]
        const newgeneralkey = keytranslatemap[keyEvent.key]
        const neverTranslated = keyEvent instanceof KeyboardEvent
        if (neverTranslated && newspecifickey !== undefined) {
            keyEvents[index] = bracketexprToKey(newspecifickey)
        } else if (newgeneralkey !== undefined)
            keyEvents[index] = newMinimalKey(keyEvent.key, { alt: ... })
        }
```

**Comment by bovine3dom** [comment]
I was leaving it open for the original problem: some keyboards use alt like shift. We should consider having a setting to ignore the alt key like we do with the shift key (unless Firefox doors it for us?).

I guess the keymap extension could work but it seems a bit messy.

**Comment by treapster** [comment]
I recently started using tridactyl and came to the same issue: non-latin layouts just don't work with it. I think to enable universal layout-agnostic support keys should be registered by KeyboardEvent.code, not key. This requires separate handling of modifiers, but why not? Applications usually implement shortcuts this way, not by directly fetching characters

**Comment by bovine3dom** [comment]
I think you're right @treapster and we should include that as an option. I imagine people would expect the keycodes to be based on the US ANSI layout?

**Comment by treapster** [comment]
@bovine3dom as far as I understand the keycodes returned by browser depend on the physical keyboard of the user. Since ANSI/ISO only differ in a couple of keys I don't think it is relevant to the issue. I think you should just register the codes and don't care where they physically come from. And even if the difference was considerable, I'm not sure if there are methods to get physical layout of user's keyboard to map it to something universal.

**Comment by bovine3dom** [comment]
Probably easiest to hard code a table like this for lookups http://microvga.com/ansi-keycodes

**Comment by treapster** [comment]
> Probably easiest to hard code a table like this for lookups http://microvga.com/ansi-keycodes

AFAIK you can't get the actual integer code because KeyboardEvent.code is a [string](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values) like "KeyA". But you don't need to, since you can match the strings in a function with a giant switch that converts "KeyX"es to 'x'es if they're printable, converts them to upper if shift is pressed and returns the resulting char.  Then instead of directly fetching KeyboardEvent.key you pass KeyboardEvent.code to that function, get the character back and use it the same way you use it now. You'll probably need to tweak it a bit to properly handle other modifiers, punctuation and non-printable chars, but overall it seems like it should work. I think i could do it and submit PR, but i ain't got the time right now.

**Comment by treapster** [comment]
Since the beta with a fix is out, i guess it's time to close the issue

**Comment by bovine3dom** [comment]
Yep! in Tridactyl `1.23.0pre6655-504f1ecb` + just run `:set keyboardlayoutforce true` to pretend that your keyboard is US QWERTY, thanks to @treapster :)
