### ISSUE TITLE
Binding <C-n> doesn't work

### ISSUE THREAD

**Issue by smoothchrome** [tridactyl/tridactyl#996]
I bound the following à la Pentadactyl:
`<C-p> tabprev`
`<C-n> tabnext`

`<C-p>` works fine and overrides the default Firefox keybinding (Print), but `<C-n>` doesn't and instead of `tabnext` it does the default Firefox keybind (New Window).

Tridactyl 1.14.0-8-gf35370a
Firefox 60.2.0 (ESR)

**Comment by bovine3dom** [comment]
It's a reserved keybind, unfortunately. The only thing we can do is find/file a bug with Mozilla and hope they look kindly on us #760.

**Comment by bovine3dom** [comment]
If you're on Linux, you could just use xkeysnail - https://github.com/mooz/xkeysnail - to rebind Ctrl-p to Ctrl-tab, and Ctrl-n to Ctrl-shift-tab. It would work on more pages than gt anyway : )

**Comment by smoothchrome** [comment]
> If you're on Linux, you could just use xkeysnail - https://github.com/mooz/xkeysnail - to rebind Ctrl-p to Ctrl-tab, and Ctrl-n to Ctrl-shift-tab. It would work on more pages than gt anyway : )

Thanks, that's a great workaround!

**Comment by ardrabczyk** [comment]
I've also tried to remap C-n in https://github.com/tridactyl/tridactyl/pull/135 and didn't know how to do that but today I use method I found at http://shallowsky.com/blog/tech/web/firefox-quantum-fixing-ctrl-w.html.  You need to kill firefox, extract browser/omni.ja to temporary directory and modify chrome/en-US/locale/browser/browser.dtd.  For example, to disable C-n replace

`<!ENTITY newNavigatorCmd.key        "N">`

with

`<!ENTITY newNavigatorCmd.key        "">`

New repack omni-ja:

`zip -qr9XD omni.ja *`

and copy it to browser directory.  I've also disabled C-p and C-[ and C-w, the full diff is:

```
< <!ENTITY printCmd.commandkey "p">
---
> <!ENTITY printCmd.commandkey "">
374c374
< <!ENTITY newNavigatorCmd.key        "N">
---
> <!ENTITY newNavigatorCmd.key        "">
765c765
< <!ENTITY goBackCmd.commandKey "[">
---
> <!ENTITY goBackCmd.commandKey "">
773c773
< <!ENTITY closeCmd.key                   "W">
---
> <!ENTITY closeCmd.key                   "">
```

Now C-w works normally in tridactyl command line, probably because I use Emacs mode in GTK config and it's possible to assign commands to C-n and C-p keybindings:

```
bind --mode=ex <C-n> ex.next_history
bind --mode=ex <C-p> ex.prev_history
bind --mode=normal <C-p> tabprev
bind --mode=normal <C-n> tabnext
```
